const appConfig: any = {
  "liveboardId": "97aa2e45-bfcb-4a76-9c81-e35c4844ebd2",
  "modelId": "ec4ee5d6-526e-4fea-931c-3399d853e7c7",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758119622,
  "app_config": {
    "menu_items": [
      "Repositories",
      "Analytics",
      "Pull Requests",
      "Issues",
      "Projects"
    ],
    "color_schema": {
      "--ts-var-root-color": "#FFFFFF",
      "--ts-var-menu-border": "#3A3B4C",
      "--ts-var-viz-background": "#2A2B3C",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#1D1E2C",
      "--ts-var-menu-item-color": "#FFFFFF",
      "--ts-var-root-background": "#1D1E2C",
      "--ts-var-root-link-color": "#FFFFFF",
      "--ts-var-viz-title-color": "#FFFFFF",
      "--ts-var-root-card-border": "#3A3B4C",
      "--ts-var-root-card-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-root-input-color": "#FFFFFF",
      "--ts-var-root-toast-color": "#FFFFFF",
      "--ts-var-root-footer-color": "#B0B0B0",
      "--ts-var-root-header-color": "#FFFFFF",
      "--ts-var-root-input-border": "#3A3B4C",
      "--ts-var-root-toast-border": "#3A3B4C",
      "--ts-var-root-toast-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-viz-border-radius": "4px",
      "--ts-var-root-tooltip-color": "#FFFFFF",
      "--ts-var-root-tooltip-border": "#3A3B4C",
      "--ts-var-root-tooltip-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-root-card-background": "#2A2B3C",
      "--ts-var-root-card-title-color": "#FFFFFF",
      "--ts-var-root-input-background": "#2A2B3C",
      "--ts-var-root-link-hover-color": "#E0E0E0",
      "--ts-var-root-toast-background": "#2A2B3C",
      "--ts-var-viz-description-color": "#B0B0B0",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-root-footer-background": "#1D1E2C",
      "--ts-var-root-footer-link-color": "#FFFFFF",
      "--ts-var-root-header-background": "#1D1E2C",
      "--ts-var-root-input-focus-color": "#FFFFFF",
      "--ts-var-root-link-active-color": "#CCCCCC",
      "--ts-var-root-toast-title-color": "#FFFFFF",
      "--ts-var-button--secondary-color": "#1D1E2C",
      "--ts-var-root-input-focus-border": "#E0E0E0",
      "--ts-var-root-tooltip-background": "#2A2B3C",
      "--ts-var-root-tooltip-arrow-color": "#2A2B3C",
      "--ts-var-spotter-input-background": "#2A2B3C",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-root-input-disabled-color": "#B0B0B0",
      "--ts-var-spotter-prompt-background": "#3A3B4C",
      "--ts-var-menu-item-hover-background": "#3A3B4C",
      "--ts-var-root-card-hover-background": "#3A3B4C",
      "--ts-var-menu-item-active-background": "#2A2B3C",
      "--ts-var-root-card-active-background": "#2A2B3C",
      "--ts-var-root-card-description-color": "#B0B0B0",
      "--ts-var-root-input-focus-background": "#3A3B4C",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#3A3B4C",
      "--ts-var-button--secondary-background": "#FFFFFF",
      "--ts-var-root-footer-link-hover-color": "#E0E0E0",
      "--ts-var-root-header-hover-background": "#3A3B4C",
      "--ts-var-root-input-placeholder-color": "#B0B0B0",
      "--ts-var-root-toast-description-color": "#B0B0B0",
      "--ts-var-root-footer-link-active-color": "#CCCCCC",
      "--ts-var-root-header-active-background": "#2A2B3C",
      "--ts-var-root-input-disabled-background": "#F0F0F0",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-disabled-color": "#B0B0B0",
      "--ts-var-button--secondary-hover-background": "#E0E0E0",
      "--ts-var-button--secondary-active-background": "#CCCCCC",
      "--ts-var-button--secondary-disabled-background": "#F0F0F0"
    }
  }
};
            export default appConfig;