const appConfig: any = {
  "liveboardId": "7f0b59c5-6d5d-4169-843a-9b60a66d8535",
  "modelId": "deffa706-71ab-4f76-801f-342178573587",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757332605,
  "color_schema": {
    "--ts-var-link-color": "#ff5a5f",
    "--ts-var-root-color": "#333333",
    "--ts-var-badge-color": "#ffffff",
    "--ts-var-card-border": "#dddddd",
    "--ts-var-card-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-menu-border": "#dddddd",
    "--ts-var-input-border": "#dddddd",
    "--ts-var-divider-color": "#dddddd",
    "--ts-var-spinner-color": "#ff5a5f",
    "--ts-var-tooltip-color": "#ffffff",
    "--ts-var-viz-background": "#f7f7f7",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-card-background": "#ffffff",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#333333",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#333333",
    "--ts-var-alert-info-color": "#0c5460",
    "--ts-var-badge-background": "#ff5a5f",
    "--ts-var-badge-box-shadow": "0 1px 3px rgba(0, 0, 0, 0.2)",
    "--ts-var-input-background": "#ffffff",
    "--ts-var-input-text-color": "#333333",
    "--ts-var-link-hover-color": "#ff4c4f",
    "--ts-var-modal-background": "#ffffff",
    "--ts-var-modal-box-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
    "--ts-var-alert-error-color": "#721c24",
    "--ts-var-link-active-color": "#ff3e40",
    "--ts-var-pagination-border": "#dddddd",
    "--ts-var-viz-border-radius": "8px",
    "--ts-var-card-border-radius": "8px",
    "--ts-var-input-focus-border": "#ff5a5f",
    "--ts-var-table-header-color": "#333333",
    "--ts-var-tooltip-background": "#333333",
    "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
    "--ts-var-alert-success-color": "#333333",
    "--ts-var-alert-warning-color": "#856404",
    "--ts-var-badge-border-radius": "12px",
    "--ts-var-modal-border-radius": "8px",
    "--ts-var-alert-info-background": "#d1ecf1",
    "--ts-var-pagination-background": "#ffffff",
    "--ts-var-pagination-item-color": "#333333",
    "--ts-var-tooltip-border-radius": "4px",
    "--ts-var-viz-description-color": "#666666",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-alert-error-background": "#f8d7da",
    "--ts-var-table-row-active-color": "#ffffff",
    "--ts-var-button--secondary-color": "#ffffff",
    "--ts-var-input-placeholder-color": "#aaaaaa",
    "--ts-var-table-header-background": "#f7f7f7",
    "--ts-var-alert-success-background": "#e0f7e0",
    "--ts-var-alert-warning-background": "#fff3cd",
    "--ts-var-modal-overlay-background": "rgba(0, 0, 0, 0.5)",
    "--ts-var-spotter-input-background": "#ffffff",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#f0f0f0",
    "--ts-var-menu-item-hover-background": "#f0f0f0",
    "--ts-var-table-row-hover-background": "#f0f0f0",
    "--ts-var-menu-item-active-background": "#ff5a5f",
    "--ts-var-table-row-active-background": "#ff5a5f",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#eaeaea",
    "--ts-var-button--secondary-background": "#ff5a5f",
    "--ts-var-pagination-item-active-color": "#ffffff",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-disabled-color": "#666666",
    "--ts-var-pagination-item-hover-background": "#f0f0f0",
    "--ts-var-pagination-item-active-background": "#ff5a5f",
    "--ts-var-button--secondary-hover-background": "#ff4c4f",
    "--ts-var-button--secondary-active-background": "#ff3e40",
    "--ts-var-button--secondary-disabled-background": "#cccccc"
  }
};
            export default appConfig;