const appConfig: any = {
  "liveboardId": "0b819075-1cc5-4455-96d3-3eaeaf77dc45",
  "modelId": "2c3f1780-2821-4cf9-b632-d6fb0acba3c5",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758025076,
  "app_config": {
    "menu_items": [
      "Home",
      "Analytics",
      "Trips",
      "Itineraries",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-root-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-viz-background": "#f6f6f6",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#000000",
      "--ts-var-viz-border-color": "#dddddd",
      "--ts-var-viz-legend-color": "#333333",
      "--ts-var-menu-border-color": "#dddddd",
      "--ts-var-viz-border-radius": "4px",
      "--ts-var-menu-item-font-size": "14px",
      "--ts-var-spotter-input-color": "#333333",
      "--ts-var-viz-title-font-size": "16px",
      "--ts-var-spotter-prompt-color": "#333333",
      "--ts-var-viz-background-hover": "#f0f0f0",
      "--ts-var-viz-box-shadow-hover": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-viz-legend-font-size": "12px",
      "--ts-var-menu-item-hover-color": "#000000",
      "--ts-var-viz-background-active": "#e0e0e0",
      "--ts-var-viz-box-shadow-active": "0 4px 8px rgba(0, 0, 0, 0.3)",
      "--ts-var-viz-description-color": "#333333",
      "--ts-var-viz-legend-background": "#ffffff",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-viz-title-hover-color": "#000000",
      "--ts-var-menu-item-active-color": "#000000",
      "--ts-var-viz-title-active-color": "#000000",
      "--ts-var-viz-title-border-color": "#dddddd",
      "--ts-var-button--secondary-color": "#000000",
      "--ts-var-spotter-input-font-size": "14px",
      "--ts-var-viz-legend-active-color": "#000000",
      "--ts-var-viz-legend-border-color": "#dddddd",
      "--ts-var-button--secondary-border": "none",
      "--ts-var-menu-item-disabled-color": "#aaaaaa",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-menu-item-hover-font-size": "14px",
      "--ts-var-spotter-prompt-background": "#f6f6f6",
      "--ts-var-viz-description-font-size": "14px",
      "--ts-var-menu-item-active-font-size": "14px",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#e0e0e0",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-description-hover-color": "#333333",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#f6eb61",
      "--ts-var-button--secondary-text-color": "#000000",
      "--ts-var-menu-item-hover-border-color": "#cccccc",
      "--ts-var-viz-description-active-color": "#333333",
      "--ts-var-viz-description-border-color": "#dddddd",
      "--ts-var-viz-legend-active-background": "#f0f0f0",
      "--ts-var-viz-title-hover-border-color": "#cccccc",
      "--ts-var-menu-item-active-border-color": "#cccccc",
      "--ts-var-menu-item-disabled-background": "#f6f6f6",
      "--ts-var-viz-legend-hover-border-color": "#cccccc",
      "--ts-var-viz-title-active-border-color": "#cccccc",
      "--ts-var-button--secondary-hover-border": "none",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-viz-legend-active-border-color": "#cccccc",
      "--ts-var-button--secondary-active-border": "none",
      "--ts-var-button--secondary-disabled-color": "#aaaaaa",
      "--ts-var-button--secondary-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-hover-text-color": "#000000",
      "--ts-var-viz-description-hover-border-color": "#cccccc",
      "--ts-var-button--secondary-active-background": "#d0d0d0",
      "--ts-var-button--secondary-active-text-color": "#000000",
      "--ts-var-viz-description-active-border-color": "#cccccc",
      "--ts-var-button--secondary-hover-border-color": "#cccccc",
      "--ts-var-button--secondary-active-border-color": "#cccccc",
      "--ts-var-button--secondary-disabled-background": "#f0f0f0",
      "--ts-var-button--secondary-disabled-border-color": "#cccccc"
    }
  }
};
            export default appConfig;