const appConfig: any = {
  "liveboardId": "eb9d0b0e-ddbb-415d-8fda-37e6653b1bdd",
  "modelId": "d6e6039a-d722-46cf-b7b6-02f68c1bfd9b",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758019159,
  "app_config": {
    "menu_items": [
      "Dashboard",
      "Analytics",
      "Listings",
      "Reservations",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-link-color": "#ff5a5f",
      "--ts-var-root-color": "#333333",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "#e0e0e0",
      "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-border": "#e0e0e0",
      "--ts-var-input-border": "#e0e0e0",
      "--ts-var-modal-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-table-border": "#e0e0e0",
      "--ts-var-badge-padding": "4px 8px",
      "--ts-var-spinner-color": "#ff5a5f",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-viz-background": "#f7f7f7",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-badge-font-size": "12px",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-badge-background": "#ff5a5f",
      "--ts-var-badge-box-shadow": "0 1px 2px rgba(0, 0, 0, 0.1)",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-link-hover-color": "#e54c52",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-alert-error-color": "#c62828",
      "--ts-var-badge-font-weight": "bold",
      "--ts-var-link-active-color": "#d14448",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-card-border-radius": "8px",
      "--ts-var-input-focus-border": "#ff5a5f",
      "--ts-var-table-cell-padding": "12px",
      "--ts-var-table-header-color": "#333333",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
      "--ts-var-alert-success-color": "#00796b",
      "--ts-var-alert-warning-color": "#ef6c00",
      "--ts-var-badge-border-radius": "12px",
      "--ts-var-modal-border-radius": "8px",
      "--ts-var-table-border-radius": "4px",
      "--ts-var-table-cell-font-size": "14px",
      "--ts-var-button--primary-color": "#ffffff",
      "--ts-var-tooltip-border-radius": "4px",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-alert-error-background": "#ffebee",
      "--ts-var-button--secondary-color": "#ff5a5f",
      "--ts-var-input-placeholder-color": "#b0b0b0",
      "--ts-var-table-header-background": "#f7f7f7",
      "--ts-var-alert-success-background": "#e0f7fa",
      "--ts-var-alert-warning-background": "#fff3e0",
      "--ts-var-modal-overlay-background": "rgba(0, 0, 0, 0.5)",
      "--ts-var-spotter-input-background": "#f0f0f0",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#ffffff",
      "--ts-var-button--primary-background": "#ff5a5f",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-table-row-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#ff5a5f",
      "--ts-var-table-row-active-background": "#eaeaea",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#eaeaea",
      "--ts-var-button--secondary-background": "#ff5a5f",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--primary-hover-background": "#e54c52",
      "--ts-var-button--primary-active-background": "#d14448",
      "--ts-var-button--secondary-hover-background": "#ff8a8f",
      "--ts-var-button--secondary-active-background": "#ff6d72"
    }
  }
};
            export default appConfig;