const appConfig: any = {
  "liveboardId": "50fb211d-9f95-4031-90b7-9017679dd690",
  "modelId": "242ec21d-7d63-473e-a1e2-71a327d63a13",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757417516,
  "color_schema": {
    "--ts-var-tab-color": "#333333",
    "--ts-var-link-color": "#ff5a5f",
    "--ts-var-root-color": "#333333",
    "--ts-var-tab-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
    "--ts-var-alert-color": "#856404",
    "--ts-var-badge-color": "#ffffff",
    "--ts-var-card-border": "#dddddd",
    "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
    "--ts-var-menu-border": "#dddddd",
    "--ts-var-alert-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
    "--ts-var-badge-shadow": "0 1px 3px rgba(0, 0, 0, 0.2)",
    "--ts-var-footer-color": "#666666",
    "--ts-var-header-color": "#333333",
    "--ts-var-input-border": "#dddddd",
    "--ts-var-modal-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
    "--ts-var-header-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
    "--ts-var-spinner-color": "#ff5a5f",
    "--ts-var-tooltip-color": "#ffffff",
    "--ts-var-tab-background": "#ffffff",
    "--ts-var-viz-background": "#f7f7f7",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-card-background": "#ffffff",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#333333",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#333333",
    "--ts-var-alert-background": "#fff3cd",
    "--ts-var-badge-background": "#ff5a5f",
    "--ts-var-breadcrumb-color": "#666666",
    "--ts-var-input-background": "#ffffff",
    "--ts-var-link-hover-color": "#e04e54",
    "--ts-var-modal-background": "#ffffff",
    "--ts-var-tab-active-color": "#ffffff",
    "--ts-var-breadcrumb-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
    "--ts-var-footer-background": "#f7f7f7",
    "--ts-var-footer-link-color": "#ff5a5f",
    "--ts-var-header-background": "#ffffff",
    "--ts-var-link-active-color": "#d1444a",
    "--ts-var-tab-border-radius": "4px",
    "--ts-var-viz-border-radius": "8px",
    "--ts-var-card-border-radius": "8px",
    "--ts-var-input-focus-border": "#ff5a5f",
    "--ts-var-progress-bar-color": "#ff5a5f",
    "--ts-var-spinner-background": "#ffffff",
    "--ts-var-tooltip-background": "#333333",
    "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
    "--ts-var-alert-border-radius": "4px",
    "--ts-var-badge-border-radius": "12px",
    "--ts-var-modal-border-radius": "8px",
    "--ts-var-breadcrumb-background": "#f7f7f7",
    "--ts-var-breadcrumb-link-color": "#ff5a5f",
    "--ts-var-tab-active-background": "#ff5a5f",
    "--ts-var-tooltip-border-radius": "4px",
    "--ts-var-viz-description-color": "#666666",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-button--secondary-color": "#ffffff",
    "--ts-var-footer-link-hover-color": "#e04e54",
    "--ts-var-input-placeholder-color": "#999999",
    "--ts-var-progress-bar-background": "#e0e0e0",
    "--ts-var-breadcrumb-border-radius": "4px",
    "--ts-var-spotter-input-background": "#f0f0f0",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#ffffff",
    "--ts-var-menu-item-hover-background": "#f0f0f0",
    "--ts-var-progress-bar-border-radius": "4px",
    "--ts-var-breadcrumb-link-hover-color": "#e04e54",
    "--ts-var-menu-item-active-background": "#ff5a5f",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#eaeaea",
    "--ts-var-button--secondary-background": "#ff5a5f",
    "--ts-var-button--secondary-text-color": "#ffffff",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-hover-background": "#e04e54",
    "--ts-var-button--secondary-text-hover-color": "#ffffff",
    "--ts-var-button--secondary-active-background": "#d1444a",
    "--ts-var-button--secondary-text-active-color": "#ffffff"
  }
};
            export default appConfig;