const appConfig: any = {
  "liveboardId": "7589c240-fbab-469f-b4ee-91a0dd17fd7e",
  "modelId": "43712ab2-321b-474b-93cb-bacc9b1d2e76",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1756916034,
  "color_schema": {
    "--ts-var-icon-color": "#172b4d",
    "--ts-var-link-color": "#0052cc",
    "--ts-var-root-color": "#172b4d",
    "--ts-var-menu-border": "#dfe1e6",
    "--ts-var-border-color": "#dfe1e6",
    "--ts-var-chart-color-1": "#36b37e",
    "--ts-var-chart-color-2": "#0052cc",
    "--ts-var-chart-color-3": "#ff5630",
    "--ts-var-chart-color-4": "#ffab00",
    "--ts-var-chart-color-5": "#dfe1e6",
    "--ts-var-tooltip-color": "#ffffff",
    "--ts-var-viz-background": "#ffffff",
    "--ts-var-viz-box-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#172b4d",
    "--ts-var-root-background": "#e6f0ff",
    "--ts-var-viz-title-color": "#172b4d",
    "--ts-var-icon-hover-color": "#0052cc",
    "--ts-var-link-hover-color": "#0747a6",
    "--ts-var-viz-border-radius": "8px",
    "--ts-var-text-primary-color": "#172b4d",
    "--ts-var-tooltip-background": "#172b4d",
    "--ts-var-text-secondary-color": "#6b778c",
    "--ts-var-button--primary-color": "#ffffff",
    "--ts-var-viz-description-color": "#172b4d",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-button--secondary-color": "#ffffff",
    "--ts-var-spotter-input-background": "#ffffff",
    "--ts-var-viz-title-text-transform": "none",
    "--ts-var-spotter-prompt-background": "#f4f5f7",
    "--ts-var-button--primary-background": "#0052cc",
    "--ts-var-menu-item-hover-background": "#e6f0ff",
    "--ts-var-menu-item-active-background": "#dfe1e6",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#f4f5f7",
    "--ts-var-button--secondary-background": "#0052cc",
    "--ts-var-viz-description-text-transform": "none"
  }
};
            export default appConfig;