const appConfig: any = {
  "liveboardId": "5c450e4d-90df-4ac3-9044-cf13d6bb6b89",
  "modelId": "e0b80634-5e29-464e-882e-8ca2636ceac0",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1758555889,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-tab-color": "#333333",
      "--ts-var-link-color": "#007a99",
      "--ts-var-root-color": "#333333",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-badge-border": "#007a99",
      "--ts-var-input-border": "#cccccc",
      "--ts-var-table-border": "#dddddd",
      "--ts-var-toast-border": "#cccccc",
      "--ts-var-divider-color": "#dddddd",
      "--ts-var-spinner-color": "#ffffff",
      "--ts-var-tab-background": "#ffffff",
      "--ts-var-tooltip-border": "#cccccc",
      "--ts-var-viz-background": "#ffffff",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-table-row-color": "#333333",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-badge-background": "#007a99",
      "--ts-var-badge-text-color": "#ffffff",
      "--ts-var-card-title-color": "#333333",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-input-text-color": "#333333",
      "--ts-var-link-hover-color": "#005f7f",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-modal-body-color": "#666666",
      "--ts-var-tab-active-color": "#007a99",
      "--ts-var-toast-background": "#ffffff",
      "--ts-var-toast-text-color": "#333333",
      "--ts-var-link-active-color": "#004d66",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-input-focus-border": "#007a99",
      "--ts-var-modal-footer-color": "#333333",
      "--ts-var-modal-header-color": "#333333",
      "--ts-var-spinner-background": "#007a99",
      "--ts-var-table-header-color": "#333333",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-tooltip-box-shadow": "0 1px 3px rgba(0, 0, 0, 0.2)",
      "--ts-var-tooltip-text-color": "#ffffff",
      "--ts-var-progress-background": "#007a99",
      "--ts-var-progress-fill-color": "#005f7f",
      "--ts-var-progress-text-color": "#ffffff",
      "--ts-var-table-row-background": "#ffffff",
      "--ts-var-tab-active-background": "#f0f0f0",
      "--ts-var-tooltip-border-radius": "4px",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-badge-hover-background": "#005f7f",
      "--ts-var-card-description-color": "#666666",
      "--ts-var-badge-active-background": "#004d66",
      "--ts-var-button--secondary-color": "#333333",
      "--ts-var-input-placeholder-color": "#999999",
      "--ts-var-modal-footer-background": "#f0f0f0",
      "--ts-var-table-header-background": "#f0f0f0",
      "--ts-var-button--secondary-border": "#cccccc",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#f0f0f0",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-table-row-hover-background": "#f7f7f7",
      "--ts-var-menu-item-active-background": "#e0e0e0",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#f7f7f7",
      "--ts-var-button--secondary-background": "#f0f0f0",
      "--ts-var-button--secondary-text-color": "#333333",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-active-background": "#d0d0d0"
    }
  }
};
            export default appConfig;