const appConfig: any = {
  "liveboardId": "1d635031-39a2-49e7-b8f6-be72a6912d3f",
  "modelId": "f2de7957-850f-4d00-80f8-a667924a9df6",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758207977,
  "app_config": {
    "menu_items": [
      "Home",
      "Analytics",
      "Travel Plans",
      "Bookings",
      "Profile"
    ],
    "color_schema": {
      "--ts-var-root-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-viz-background": "#f0f0f0",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-viz-border-color": "#dddddd",
      "--ts-var-viz-legend-color": "#333333",
      "--ts-var-viz-border-radius": "4px",
      "--ts-var-viz-legend-border": "#cccccc",
      "--ts-var-menu-border-radius": "4px",
      "--ts-var-menu-item-font-size": "14px",
      "--ts-var-spotter-input-color": "#333333",
      "--ts-var-viz-title-font-size": "16px",
      "--ts-var-spotter-input-border": "#cccccc",
      "--ts-var-spotter-prompt-color": "#333333",
      "--ts-var-viz-background-hover": "#ffffff",
      "--ts-var-viz-box-shadow-hover": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-viz-legend-font-size": "12px",
      "--ts-var-menu-item-font-weight": "normal",
      "--ts-var-menu-item-hover-color": "#000000",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-legend-background": "#f0f0f0",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-viz-title-font-weight": "bold",
      "--ts-var-viz-title-hover-color": "#000000",
      "--ts-var-menu-item-active-color": "#000000",
      "--ts-var-viz-legend-font-weight": "normal",
      "--ts-var-button--secondary-color": "#333333",
      "--ts-var-spotter-input-font-size": "14px",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-spotter-prompt-font-size": "14px",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#f6eb61",
      "--ts-var-viz-description-font-size": "14px",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-spotter-input-hover-border": "#aaaaaa",
      "--ts-var-spotter-prompt-font-weight": "bold",
      "--ts-var-button--secondary-font-size": "14px",
      "--ts-var-menu-item-active-background": "#f6eb61",
      "--ts-var-menu-item-hover-font-weight": "bold",
      "--ts-var-spotter-input-active-border": "#888888",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-description-font-weight": "normal",
      "--ts-var-viz-description-hover-color": "#444444",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#f6eb61",
      "--ts-var-button--secondary-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-item-active-font-weight": "bold",
      "--ts-var-button--secondary-color-hover": "#000000",
      "--ts-var-button--secondary-font-weight": "bold",
      "--ts-var-button--secondary-color-active": "#000000",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-border-radius": "4px",
      "--ts-var-button--secondary-box-shadow-hover": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-button--secondary-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-active-background": "#d1d100",
      "--ts-var-button--secondary-box-shadow-active": "0 4px 8px rgba(0, 0, 0, 0.3)"
    }
  }
};
            export default appConfig;