const appConfig: any = {
  "liveboardId": "64606730-291d-48fe-815f-45f6f056af43",
  "modelId": "4d8f1566-acc3-4e57-b115-4b4ff0e142cd",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757580005,
  "color_schema": {
    "--ts-var-link-color": "#0072E5",
    "--ts-var-root-color": "#1D1D1D",
    "--ts-var-badge-color": "#ffffff",
    "--ts-var-card-border": "#d9d9d9",
    "--ts-var-card-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-input-color": "#1D1D1D",
    "--ts-var-menu-border": "#d9d9d9",
    "--ts-var-toast-color": "#1D1D1D",
    "--ts-var-badge-shadow": "0 1px 2px rgba(0, 0, 0, 0.1)",
    "--ts-var-input-border": "#d9d9d9",
    "--ts-var-modal-border": "#d9d9d9",
    "--ts-var-modal-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
    "--ts-var-table-border": "#d9d9d9",
    "--ts-var-toast-border": "#d9d9d9",
    "--ts-var-toast-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-divider-color": "#d9d9d9",
    "--ts-var-spinner-color": "#0072E5",
    "--ts-var-tooltip-color": "#ffffff",
    "--ts-var-progress-color": "#0072E5",
    "--ts-var-viz-background": "#f9f9f9",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-card-background": "#ffffff",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#1D1D1D",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#1D1D1D",
    "--ts-var-badge-background": "#0072E5",
    "--ts-var-input-background": "#ffffff",
    "--ts-var-link-hover-color": "#005bb5",
    "--ts-var-modal-background": "#ffffff",
    "--ts-var-toast-background": "#ffffff",
    "--ts-var-divider-thickness": "1px",
    "--ts-var-link-active-color": "#004a90",
    "--ts-var-table-row-padding": "12px",
    "--ts-var-tooltip-font-size": "12px",
    "--ts-var-viz-border-radius": "8px",
    "--ts-var-input-focus-border": "#0072E5",
    "--ts-var-spinner-background": "#ffffff",
    "--ts-var-table-cell-padding": "12px",
    "--ts-var-table-header-color": "#1D1D1D",
    "--ts-var-tooltip-background": "#333333",
    "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
    "--ts-var-badge-border-radius": "12px",
    "--ts-var-progress-background": "#e0e0e0",
    "--ts-var-table-row-font-size": "14px",
    "--ts-var-tooltip-font-family": "Arial, sans-serif",
    "--ts-var-table-header-padding": "16px",
    "--ts-var-spinner-border-radius": "50%",
    "--ts-var-table-row-font-family": "Arial, sans-serif",
    "--ts-var-tooltip-border-radius": "4px",
    "--ts-var-viz-description-color": "#4A4A4A",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-progress-border-radius": "4px",
    "--ts-var-table-header-font-size": "14px",
    "--ts-var-button--secondary-color": "#ffffff",
    "--ts-var-input-placeholder-color": "#b0b0b0",
    "--ts-var-table-header-background": "#f9f9f9",
    "--ts-var-spotter-input-background": "#ffffff",
    "--ts-var-table-header-font-family": "Arial, sans-serif",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#f0f0f0",
    "--ts-var-menu-item-hover-background": "#e0e0e0",
    "--ts-var-table-row-hover-background": "#f0f0f0",
    "--ts-var-menu-item-active-background": "#0072E5",
    "--ts-var-table-row-active-background": "#e0e0e0",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#e0e0e0",
    "--ts-var-button--secondary-background": "#0072E5",
    "--ts-var-button--secondary-hover-color": "#ffffff",
    "--ts-var-button--secondary-active-color": "#ffffff",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-hover-background": "#005bb5",
    "--ts-var-button--secondary-active-background": "#004a90"
  }
};
            export default appConfig;