const appConfig: any = {
  "liveboardId": "5484cad0-f4bf-4eed-b677-bc5abeffcbac",
  "modelId": "353dc4b5-b2dc-405e-b22f-09a811b4ade8",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758178428,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-body-color": "#666666",
      "--ts-var-link-color": "#ff5a5f",
      "--ts-var-root-color": "#333333",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-card-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-input-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-input-border": "#dddddd",
      "--ts-var-shadow-large": "0 4px 8px rgba(0, 0, 0, 0.1)",
      "--ts-var-shadow-small": "0 1px 2px rgba(0, 0, 0, 0.1)",
      "--ts-var-heading-color": "#333333",
      "--ts-var-shadow-medium": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-spacing-large": "24px",
      "--ts-var-spacing-small": "8px",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-body-font-size": "16px",
      "--ts-var-spacing-medium": "16px",
      "--ts-var-viz-background": "#f7f7f7",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-highlight-color": "#ff5a5f",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-body-font-family": "Arial, sans-serif",
      "--ts-var-body-line-height": "1.5",
      "--ts-var-highlight-border": "#ff5a5f",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-input-box-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-link-hover-color": "#ff474c",
      "--ts-var-card-hover-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-heading-font-size": "24px",
      "--ts-var-link-active-color": "#ff3b40",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-card-active-shadow": "0 4px 8px rgba(0, 0, 0, 0.3)",
      "--ts-var-card-border-radius": "8px",
      "--ts-var-input-focus-border": "#ff5a5f",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-border-radius-large": "12px",
      "--ts-var-border-radius-small": "4px",
      "--ts-var-heading-font-family": "Arial, sans-serif",
      "--ts-var-heading-font-weight": "bold",
      "--ts-var-input-border-radius": "4px",
      "--ts-var-border-radius-medium": "8px",
      "--ts-var-highlight-background": "#ffe6e6",
      "--ts-var-highlight-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-tooltip-border-radius": "4px",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-button--secondary-color": "#ffffff",
      "--ts-var-highlight-border-radius": "4px",
      "--ts-var-input-placeholder-color": "#999999",
      "--ts-var-button--secondary-border": "none",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#f0f0f0",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#ff5a5f",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#ff5a5f",
      "--ts-var-button--secondary-text-color": "#ffffff",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-hover-background": "#ff474c",
      "--ts-var-button--secondary-hover-text-color": "#ffffff",
      "--ts-var-button--secondary-active-background": "#ff3b40",
      "--ts-var-button--secondary-active-text-color": "#ffffff"
    }
  }
};
            export default appConfig;