const appConfig: any = {
  "liveboardId": "1c1c37ed-13d9-4637-b062-6205b77c3373",
  "modelId": "22bbcdc1-ad89-48d6-979f-ac09abdb7aff",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1759990260,
  "color_schema": {
    "--ts-var-nav-color": "#ffffff",
    "--ts-var-link-color": "#ff385c",
    "--ts-var-root-color": "#484848",
    "--ts-var-card-border": "#e0e0e0",
    "--ts-var-menu-border": "#e0e0e0",
    "--ts-var-toast-color": "#ffffff",
    "--ts-var-footer-color": "#484848",
    "--ts-var-header-color": "#484848",
    "--ts-var-input-border": "#e0e0e0",
    "--ts-var-divider-color": "#e0e0e0",
    "--ts-var-spinner-color": "#ff385c",
    "--ts-var-tooltip-color": "#ffffff",
    "--ts-var-nav-background": "#800080",
    "--ts-var-spinner-border": "#e0e0e0",
    "--ts-var-viz-background": "#ffffff",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-card-background": "#ffffff",
    "--ts-var-card-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#484848",
    "--ts-var-nav-hover-color": "#ff385c",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#484848",
    "--ts-var-input-background": "#f7f7f7",
    "--ts-var-link-hover-color": "#d32f2f",
    "--ts-var-modal-background": "#ffffff",
    "--ts-var-modal-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
    "--ts-var-toast-background": "#484848",
    "--ts-var-toast-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
    "--ts-var-footer-background": "#f7f7f7",
    "--ts-var-footer-link-color": "#ff385c",
    "--ts-var-header-background": "#ffffff",
    "--ts-var-link-active-color": "#c62828",
    "--ts-var-viz-border-radius": "4px",
    "--ts-var-card-border-radius": "4px",
    "--ts-var-input-focus-border": "#ff385c",
    "--ts-var-modal-footer-color": "#484848",
    "--ts-var-modal-header-color": "#484848",
    "--ts-var-spinner-background": "#ffffff",
    "--ts-var-tooltip-background": "#484848",
    "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
    "--ts-var-modal-border-radius": "4px",
    "--ts-var-toast-border-radius": "4px",
    "--ts-var-footer-divider-color": "#e0e0e0",
    "--ts-var-tooltip-border-radius": "4px",
    "--ts-var-viz-description-color": "#484848",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-input-focus-background": "#ffffff",
    "--ts-var-button--secondary-color": "#ff385c",
    "--ts-var-footer-link-hover-color": "#d32f2f",
    "--ts-var-header-hover-background": "#f7f7f7",
    "--ts-var-input-placeholder-color": "#b0b0b0",
    "--ts-var-modal-footer-background": "#f7f7f7",
    "--ts-var-modal-header-background": "#ffffff",
    "--ts-var-header-active-background": "#ff385c",
    "--ts-var-modal-overlay-background": "rgba(0, 0, 0, 0.5)",
    "--ts-var-spotter-input-background": "#f7f7f7",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#ffffff",
    "--ts-var-menu-item-hover-background": "#f7f7f7",
    "--ts-var-menu-item-active-background": "#ff385c",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#f7f7f7",
    "--ts-var-button--secondary-background": "#f7f7f7",
    "--ts-var-button--secondary-text-color": "#484848",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-hover-background": "#e0e0e0",
    "--ts-var-button--secondary-hover-text-color": "#ff385c",
    "--ts-var-button--secondary-active-background": "#d0d0d0",
    "--ts-var-button--secondary-active-text-color": "#ff385c"
  },
  "menu_items": [
    "Dashboard",
    "Analytics",
    "Listings",
    "Reservations",
    "Admin"
  ]
};
            export default appConfig;