const appConfig: any = {
  "liveboardId": "4d9fb40e-881a-4880-9cbc-a93e2b5c2ba5",
  "modelId": "0d295e1a-b7bf-46ed-848c-d86bd224a5d9",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1760929909,
  "app_config": {
    "menu_items": [
      "Dashboard",
      "Analytics",
      "Policies",
      "Claims",
      "Renewals",
      "Profile"
    ],
    "color_schema": {
      "--ts-var-shadow-1": "0px 2px 6px 0px rgba(35,35,35,0.03)",
      "--ts-var-shadow-2": "0px 4px 16px 0px rgba(35,35,35,0.06)",
      "--ts-var-shadow-3": "0px 4px 24px 0px rgba(35,35,35,0.09)",
      "--ts-var-nav-color": "#fff",
      "--ts-var-tab-color": "#232323",
      "--ts-var-tag-color": "#ee7632",
      "--ts-var-chip-color": "#ee7632",
      "--ts-var-link-color": "#005195",
      "--ts-var-root-color": "#232323",
      "--ts-var-spacing-lg": "24px",
      "--ts-var-spacing-md": "16px",
      "--ts-var-spacing-sm": "8px",
      "--ts-var-spacing-xl": "32px",
      "--ts-var-spacing-xs": "4px",
      "--ts-var-tag-border": "#ffb476",
      "--ts-var-badge-color": "#fff",
      "--ts-var-card-border": "#f1e6df",
      "--ts-var-chip-border": "#fde6d6",
      "--ts-var-input-color": "#232323",
      "--ts-var-menu-border": "#f1e6df",
      "--ts-var-spacing-xxl": "48px",
      "--ts-var-spacing-xxs": "2px",
      "--ts-var-appbar-color": "#fff",
      "--ts-var-avatar-color": "#ee7632",
      "--ts-var-input-border": "#ebebeb",
      "--ts-var-modal-border": "#ffb476",
      "--ts-var-table-border": "#f1e6df",
      "--ts-var-divider-color": "#f1e6df",
      "--ts-var-focus-outline": "#ee7632",
      "--ts-var-popover-color": "#232323",
      "--ts-var-tooltip-color": "#232323",
      "--ts-var-nav-background": "#ee7632",
      "--ts-var-popover-border": "#f1e6df",
      "--ts-var-progress-color": "#ee7632",
      "--ts-var-tab-background": "#fff",
      "--ts-var-tag-background": "#fde6d6",
      "--ts-var-tooltip-border": "#fde6d6",
      "--ts-var-viz-background": "#fff",
      "--ts-var-viz-box-shadow": "0px 2px 6px 0px rgba(35,35,35,0.03)",
      "--ts-var-card-background": "#fff",
      "--ts-var-card-box-shadow": "0px 2px 6px 0px rgba(35,35,35,0.03)",
      "--ts-var-chip-background": "#fde6d6",
      "--ts-var-menu-background": "#fff",
      "--ts-var-menu-item-color": "#232323",
      "--ts-var-nav-hover-color": "#ffb476",
      "--ts-var-root-background": "#faf8f7",
      "--ts-var-scrollbar-thumb": "#f1e6df",
      "--ts-var-scrollbar-track": "#fff6ef",
      "--ts-var-viz-title-color": "#232323",
      "--ts-var-alert-info-color": "#1253a4",
      "--ts-var-badge-background": "#ee7632",
      "--ts-var-form-error-color": "#e33c1b",
      "--ts-var-form-label-color": "#232323",
      "--ts-var-input-background": "#fff",
      "--ts-var-link-hover-color": "#003a6c",
      "--ts-var-modal-background": "#fff",
      "--ts-var-nav-active-color": "#eb620d",
      "--ts-var-tab-active-color": "#ee7632",
      "--ts-var-table-cell-color": "#232323",
      "--ts-var-alert-error-color": "#e33c1b",
      "--ts-var-appbar-background": "#ee7632",
      "--ts-var-avatar-background": "#fde6d6",
      "--ts-var-filter-background": "#fff6ef",
      "--ts-var-filter-chip-color": "#ee7632",
      "--ts-var-viz-border-radius": "16px",
      "--ts-var-viz-control-color": "#ee7632",
      "--ts-var-viz-tooltip-color": "#232323",
      "--ts-var-card-border-radius": "16px",
      "--ts-var-form-success-color": "#439242",
      "--ts-var-input-focus-border": "#ee7632",
      "--ts-var-modal-header-color": "#232323",
      "--ts-var-popover-background": "#fff",
      "--ts-var-skeleton-highlight": "#fde6d6",
      "--ts-var-tab-inactive-color": "#8f8a85",
      "--ts-var-table-header-color": "#232323",
      "--ts-var-tooltip-background": "#fff",
      "--ts-var-viz-control-border": "#ffb476",
      "--ts-var-viz-tooltip-border": "#fde6d6",
      "--ts-var-alert-success-color": "#257943",
      "--ts-var-alert-warning-color": "#ee7632",
      "--ts-var-chip-selected-color": "#c5400e",
      "--ts-var-progress-background": "#fde6d6",
      "--ts-var-root-tertiary-color": "#8f8a85",
      "--ts-var-skeleton-background": "#f1e6df",
      "--ts-var-spotter-input-color": "#232323",
      "--ts-var-viz-axis-line-color": "#f1e6df",
      "--ts-var-viz-grid-line-color": "#f1e6df",
      "--ts-var-appbar-border-bottom": "#c5400e",
      "--ts-var-root-secondary-color": "#55565a",
      "--ts-var-spotter-input-border": "#ee7632",
      "--ts-var-alert-info-background": "#ddeaf9",
      "--ts-var-chip-hover-background": "#ffb476",
      "--ts-var-tab-active-background": "#fde6d6",
      "--ts-var-viz-description-color": "#55565a",
      "--ts-var-viz-title-font-family": "Inter, Arial, sans-serif",
      "--ts-var-alert-error-background": "#fce8e0",
      "--ts-var-button--disabled-color": "#8f8a85",
      "--ts-var-button--tertiary-color": "#ee7632",
      "--ts-var-filter-chip-background": "#fde6d6",
      "--ts-var-form-helper-text-color": "#8f8a85",
      "--ts-var-radio-unchecked-border": "#8f8a85",
      "--ts-var-viz-control-background": "#fde6d6",
      "--ts-var-viz-label-accent-color": "#ee7632",
      "--ts-var-viz-legend-label-color": "#232323",
      "--ts-var-viz-tooltip-background": "#fff",
      "--ts-var-button--secondary-color": "#ee7632",
      "--ts-var-button--tertiary-border": "#fde6d6",
      "--ts-var-input-placeholder-color": "#8f8a85",
      "--ts-var-modal-footer-background": "#fde6d6",
      "--ts-var-tab-inactive-background": "#fff",
      "--ts-var-table-header-background": "#fde6d6",
      "--ts-var-viz-control-hover-color": "#c5400e",
      "--ts-var-viz-label-primary-color": "#232323",
      "--ts-var-alert-success-background": "#dbf0df",
      "--ts-var-alert-warning-background": "#fff6ef",
      "--ts-var-button--secondary-border": "#ee7632",
      "--ts-var-chip-selected-background": "#ffb476",
      "--ts-var-filter-chip-active-color": "#c5400e",
      "--ts-var-modal-overlay-background": "rgba(35,35,35,0.54)",
      "--ts-var-radio-checked-background": "#ee7632",
      "--ts-var-spotter-input-background": "#fff",
      "--ts-var-spotter-suggestion-color": "#232323",
      "--ts-var-table-row-selected-color": "#c5400e",
      "--ts-var-viz-title-text-transform": "none",
      "--ts-var-checkbox-unchecked-border": "#8f8a85",
      "--ts-var-spotter-prompt-background": "#fde6d6",
      "--ts-var-switch-checked-background": "#ee7632",
      "--ts-var-table-skeleton-background": "#f1e6df",
      "--ts-var-viz-label-secondary-color": "#8f8a85",
      "--ts-var-menu-item-hover-background": "#fde6d6",
      "--ts-var-table-row-hover-background": "#ffb476",
      "--ts-var-button--disabled-background": "#f1e6df",
      "--ts-var-button--tertiary-background": "#fff",
      "--ts-var-checkbox-checked-background": "#ee7632",
      "--ts-var-menu-item-active-background": "#ffb476",
      "--ts-var-switch-unchecked-background": "#d6d6d6",
      "--ts-var-table-row-active-background": "#ffb476",
      "--ts-var-viz-description-font-family": "Inter, Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#fde6d6",
      "--ts-var-button--secondary-background": "#fde6d6",
      "--ts-var-button--tertiary-hover-color": "#c5400e",
      "--ts-var-checkbox-disabled-background": "#f1e6df",
      "--ts-var-viz-control-hover-background": "#ffb476",
      "--ts-var-button--secondary-hover-color": "#c5400e",
      "--ts-var-button--tertiary-active-color": "#c5400e",
      "--ts-var-filter-chip-active-background": "#ffb476",
      "--ts-var-spotter-suggestion-background": "#fde6d6",
      "--ts-var-table-row-selected-background": "#fde6d6",
      "--ts-var-button--secondary-active-color": "#fff",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-spotter-input-placeholder-color": "#8f8a85",
      "--ts-var-button--tertiary-hover-background": "#fde6d6",
      "--ts-var-button--secondary-hover-background": "#ffb476",
      "--ts-var-button--tertiary-active-background": "#ffb476",
      "--ts-var-button--secondary-active-background": "#eb620d",
      "--ts-var-spotter-suggestion-hover-background": "#ffb476"
    }
  }
};
            export default appConfig;