const appConfig: any = {
  "liveboardId": "24b3bef3-b5d8-4011-b093-d6a97c9603b6",
  "modelId": "bd00eec4-08e9-4f71-8869-e233d6c165b5",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1760094014,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#333333",
      "--ts-var-link-color": "#FF5A5F",
      "--ts-var-nav-border": "#E0E0E0",
      "--ts-var-root-color": "#333333",
      "--ts-var-tag-border": "#FF5A5F",
      "--ts-var-viz-border": "#E0E0E0",
      "--ts-var-card-border": "#E0E0E0",
      "--ts-var-card-shadow": "0 2px 5px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-border": "#E0E0E0",
      "--ts-var-footer-color": "#666666",
      "--ts-var-header-color": "#333333",
      "--ts-var-input-border": "#E0E0E0",
      "--ts-var-rating-color": "#FFCC00",
      "--ts-var-divider-color": "#E0E0E0",
      "--ts-var-tooltip-color": "#FFFFFF",
      "--ts-var-nav-background": "#F5F5F5",
      "--ts-var-tag-background": "#FFE0E1",
      "--ts-var-viz-background": "#f8f8f8",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#FFFFFF",
      "--ts-var-highlight-color": "#FF5A5F",
      "--ts-var-menu-background": "#FFFFFF",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#FFFFFF",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-input-background": "#FFFFFF",
      "--ts-var-link-hover-color": "#FF8A8F",
      "--ts-var-menu-item-border": "#E0E0E0",
      "--ts-var-modal-background": "#FFFFFF",
      "--ts-var-modal-box-shadow": "0 5px 15px rgba(0, 0, 0, 0.3)",
      "--ts-var-card-focus-border": "#FF5A5F",
      "--ts-var-footer-background": "#F5F5F5",
      "--ts-var-footer-link-color": "#FF5A5F",
      "--ts-var-header-background": "#FFFFFF",
      "--ts-var-table-cell-border": "#E0E0E0",
      "--ts-var-viz-border-radius": "6px",
      "--ts-var-input-focus-border": "#FF5A5F",
      "--ts-var-primary-text-color": "#333333",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.15)",
      "--ts-var-spotter-input-color": "#333333",
      "--ts-var-highlight-background": "#FFF0F0",
      "--ts-var-nav-hover-background": "#E0E0E0",
      "--ts-var-root-secondary-color": "#666666",
      "--ts-var-secondary-text-color": "#666666",
      "--ts-var-spotter-prompt-color": "#FF5A5F",
      "--ts-var-button--primary-color": "#FFFFFF",
      "--ts-var-card-hover-background": "#F5F5F5",
      "--ts-var-menu-item-color-hover": "#FF5A5F",
      "--ts-var-tooltip-border-radius": "4px",
      "--ts-var-viz-box-shadow-active": "0 4px 8px rgba(0, 0, 0, 0.15)",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-viz-title-hover-color": "#FF5A5F",
      "--ts-var-card-active-background": "#E0E0E0",
      "--ts-var-menu-background-active": "#FF5A5F",
      "--ts-var-menu-item-color-active": "#FFFFFF",
      "--ts-var-button--secondary-color": "#FFFFFF",
      "--ts-var-footer-link-hover-color": "#FF8A8F",
      "--ts-var-header-hover-background": "#F5F5F5",
      "--ts-var-table-header-background": "#F5F5F5",
      "--ts-var-card-disabled-background": "#F5F5F5",
      "--ts-var-menu-item-disabled-color": "#CCCCCC",
      "--ts-var-spotter-input-background": "#FFFFFF",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-input-disabled-background": "#F5F5F5",
      "--ts-var-spotter-prompt-background": "#FFE0E1",
      "--ts-var-button--primary-background": "#FF5A5F",
      "--ts-var-menu-item-hover-background": "#F5F5F5",
      "--ts-var-table-row-hover-background": "#F0F0F0",
      "--ts-var-menu-item-active-background": "#FF5A5F",
      "--ts-var-table-row-active-background": "#E0E0E0",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-description-hover-color": "#333333",
      "--ts-var-viz-legend-hover-background": "#F5F5F5",
      "--ts-var-button--secondary-background": "#FF5A5F",
      "--ts-var-menu-item-disabled-background": "#F5F5F5",
      "--ts-var-button--primary-disabled-color": "#FFFFFF",
      "--ts-var-button--secondary-focus-border": "#FF5A5F",
      "--ts-var-viz-description-text-transform": "capitalize",
      "--ts-var-button--secondary-disabled-color": "#FFFFFF",
      "--ts-var-button--secondary-hover-background": "#FF8A8F",
      "--ts-var-button--primary-disabled-background": "rgba(255, 90, 95, 0.5)",
      "--ts-var-button--secondary-active-background": "#FF4D4F",
      "--ts-var-button--secondary-disabled-background": "rgba(255, 90, 95, 0.5)"
    }
  }
};
            export default appConfig;