const appConfig: any = {
  "liveboardId": "5b2a2c7a-690b-45b2-9fc2-b8b3ffcc9345",
  "modelId": "1214ad64-8be1-4481-8f57-5a96298da445",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1759992427,
  "app_config": {
    "menu_items": [
      "Dashboard",
      "Analytics",
      "Products",
      "Orders",
      "Customers",
      "Settings"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#00695C",
      "--ts-var-link-color": "#009688",
      "--ts-var-root-color": "#004D40",
      "--ts-var-badge-color": "#FFFFFF",
      "--ts-var-card-border": "1px solid #B2EBF2",
      "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-input-color": "#004D40",
      "--ts-var-menu-border": "1px solid #B2EBF2",
      "--ts-var-badge-border": "1px solid #B2EBF2",
      "--ts-var-footer-color": "#004D40",
      "--ts-var-header-color": "#004D40",
      "--ts-var-input-border": "1px solid #B2EBF2",
      "--ts-var-table-border": "1px solid #B2EBF2",
      "--ts-var-divider-color": "#B2EBF2",
      "--ts-var-spinner-color": "#FFFFFF",
      "--ts-var-tooltip-color": "#004D40",
      "--ts-var-nav-background": "#B2EBF2",
      "--ts-var-tooltip-border": "1px solid #B2EBF2",
      "--ts-var-viz-background": "#FFFFFF",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#FFFFFF",
      "--ts-var-menu-background": "#B2EBF2",
      "--ts-var-menu-item-color": "#004D40",
      "--ts-var-nav-hover-color": "#004D40",
      "--ts-var-root-background": "#E0F7FA",
      "--ts-var-viz-title-color": "#004D40",
      "--ts-var-alert-info-color": "#1976D2",
      "--ts-var-badge-background": "#009688",
      "--ts-var-breadcrumb-color": "#004D40",
      "--ts-var-input-background": "#FFFFFF",
      "--ts-var-link-hover-color": "#00796B",
      "--ts-var-modal-background": "#FFFFFF",
      "--ts-var-alert-error-color": "#D32F2F",
      "--ts-var-footer-background": "#B2EBF2",
      "--ts-var-header-background": "#B2EBF2",
      "--ts-var-viz-border-radius": "4px",
      "--ts-var-modal-footer-color": "#004D40",
      "--ts-var-modal-header-color": "#004D40",
      "--ts-var-spinner-background": "#009688",
      "--ts-var-table-header-color": "#004D40",
      "--ts-var-tooltip-background": "#FFFFFF",
      "--ts-var-alert-success-color": "#004D40",
      "--ts-var-alert-warning-color": "#FF9800",
      "--ts-var-table-row-background": "#FFFFFF",
      "--ts-var-alert-info-background": "#E3F2FD",
      "--ts-var-breadcrumb-background": "#B2EBF2",
      "--ts-var-button--primary-color": "#FFFFFF",
      "--ts-var-viz-description-color": "#004D40",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-alert-error-background": "#FFEBEE",
      "--ts-var-badge-hover-background": "#00796B",
      "--ts-var-breadcrumb-hover-color": "#00796B",
      "--ts-var-breadcrumb-active-color": "#009688",
      "--ts-var-button--secondary-color": "#004D40",
      "--ts-var-input-placeholder-color": "#B2EBF2",
      "--ts-var-modal-footer-background": "#B2EBF2",
      "--ts-var-modal-header-background": "#B2EBF2",
      "--ts-var-table-header-background": "#E0F7FA",
      "--ts-var-alert-success-background": "#E0F7FA",
      "--ts-var-alert-warning-background": "#FFF3E0",
      "--ts-var-spotter-input-background": "#FFFFFF",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#B2EBF2",
      "--ts-var-button--primary-background": "#009688",
      "--ts-var-menu-item-hover-background": "#E0F7FA",
      "--ts-var-table-row-hover-background": "#B2EBF2",
      "--ts-var-menu-item-active-background": "#B2EBF2",
      "--ts-var-table-row-active-background": "#E0F7FA",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#B2EBF2",
      "--ts-var-button--secondary-background": "#FFFFFF",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--primary-hover-background": "#00796B",
      "--ts-var-button--secondary-hover-background": "#E0F7FA"
    }
  }
};
            export default appConfig;