const appConfig: any = {
  "liveboardId": "451e9ac4-e368-4e5d-933c-50dcf5e04617",
  "modelId": "485b0feb-16b4-4594-b11c-0b8627ddd6a2",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1756914607,
  "color_schema": {
    "--ts-var-link-color": "#007eeb",
    "--ts-var-root-color": "#000000",
    "--ts-var-badge-color": "#000000",
    "--ts-var-card-border": "#dcdcdc",
    "--ts-var-card-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-menu-border": "#dcdcdc",
    "--ts-var-footer-color": "#4a4a4a",
    "--ts-var-header-color": "#000000",
    "--ts-var-input-border": "#dcdcdc",
    "--ts-var-modal-border": "#dcdcdc",
    "--ts-var-modal-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-table-border": "#dcdcdc",
    "--ts-var-avatar-border": "#dcdcdc",
    "--ts-var-avatar-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-footer-border": "#dcdcdc",
    "--ts-var-header-border": "#dcdcdc",
    "--ts-var-tooltip-color": "#ffffff",
    "--ts-var-tooltip-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-viz-background": "#ffffff",
    "--ts-var-viz-box-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-card-background": "#ffffff",
    "--ts-var-dropdown-border": "#dcdcdc",
    "--ts-var-dropdown-shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#000000",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#000000",
    "--ts-var-badge-background": "#fdbd10",
    "--ts-var-input-background": "#ffffff",
    "--ts-var-link-hover-color": "#005bb5",
    "--ts-var-modal-background": "#ffffff",
    "--ts-var-avatar-background": "#f0f0f0",
    "--ts-var-footer-background": "#f8f8f8",
    "--ts-var-header-background": "#ffffff",
    "--ts-var-progress-bar-fill": "#007eeb",
    "--ts-var-switch-background": "#dcdcdc",
    "--ts-var-viz-border-radius": "4px",
    "--ts-var-brand-accent-color": "#fdbd10",
    "--ts-var-input-focus-border": "#007eeb",
    "--ts-var-notification-color": "#4a4a4a",
    "--ts-var-table-header-color": "#000000",
    "--ts-var-tooltip-background": "#000000",
    "--ts-var-dropdown-background": "#ffffff",
    "--ts-var-notification-border": "#dcdcdc",
    "--ts-var-slider-thumb-border": "#ffffff",
    "--ts-var-root-secondary-color": "#4a4a4a",
    "--ts-var-table-row-background": "#ffffff",
    "--ts-var-button--primary-color": "#ffffff",
    "--ts-var-viz-description-color": "#000000",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-input-placeholder-color": "#a0a0a0",
    "--ts-var-notification-background": "#f8f8f8",
    "--ts-var-progress-bar-background": "#f0f0f0",
    "--ts-var-slider-thumb-background": "#007eeb",
    "--ts-var-slider-track-background": "#dcdcdc",
    "--ts-var-switch-thumb-background": "#ffffff",
    "--ts-var-table-header-background": "#f0f0f0",
    "--ts-var-spotter-input-background": "#ffffff",
    "--ts-var-switch-active-background": "#007eeb",
    "--ts-var-viz-title-text-transform": "none",
    "--ts-var-spotter-prompt-background": "#ffffff",
    "--ts-var-button--primary-background": "#007eeb",
    "--ts-var-menu-item-hover-background": "#f0f0f0",
    "--ts-var-table-row-hover-background": "#f8f8f8",
    "--ts-var-menu-item-active-background": "#e0e0e0",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#f0f0f0",
    "--ts-var-button--secondary-background": "#007eeb",
    "--ts-var-switch-active-thumb-background": "#ffffff",
    "--ts-var-viz-description-text-transform": "none"
  }
};
            export default appConfig;