const appConfig: any = {
  "liveboardId": "1e28876f-ea95-489c-8ce6-d57295c51c81",
  "modelId": "cfccb77a-0683-4f4d-98e2-7b87cdc87c58",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1758551070,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-link-color": "#007a99",
      "--ts-var-root-color": "#333333",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-hover-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-active-color": "#333333",
      "--ts-var-input-border": "#cccccc",
      "--ts-var-shadow-large": "0 4px 8px rgba(0, 0, 0, 0.1)",
      "--ts-var-shadow-small": "0 1px 2px rgba(0, 0, 0, 0.1)",
      "--ts-var-focus-outline": "2px solid #007a99",
      "--ts-var-heading-color": "#333333",
      "--ts-var-shadow-medium": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-spacing-large": "24px",
      "--ts-var-spacing-small": "8px",
      "--ts-var-body-font-size": "1rem",
      "--ts-var-disabled-color": "#cccccc",
      "--ts-var-spacing-medium": "16px",
      "--ts-var-tooltip-border": "#cccccc",
      "--ts-var-viz-background": "#ffffff",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-disabled-border": "#dddddd",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-body-font-family": "Arial, sans-serif",
      "--ts-var-body-font-weight": "normal",
      "--ts-var-hover-background": "#f0f0f0",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-input-text-color": "#333333",
      "--ts-var-link-hover-color": "#005f7f",
      "--ts-var-active-background": "#e0e0e0",
      "--ts-var-card-hover-shadow": "0 2px 4px rgba(0, 0, 0, 0.2)",
      "--ts-var-heading-font-size": "1.5rem",
      "--ts-var-input-error-color": "#ff4d4d",
      "--ts-var-link-active-color": "#004d66",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-card-active-shadow": "0 2px 4px rgba(0, 0, 0, 0.3)",
      "--ts-var-card-border-radius": "8px",
      "--ts-var-input-focus-border": "#007a99",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-tooltip-text-color": "#ffffff",
      "--ts-var-border-radius-large": "12px",
      "--ts-var-border-radius-small": "4px",
      "--ts-var-disabled-background": "#f0f0f0",
      "--ts-var-heading-font-family": "Arial, sans-serif",
      "--ts-var-heading-font-weight": "bold",
      "--ts-var-tooltip-arrow-color": "#333333",
      "--ts-var-border-radius-medium": "8px",
      "--ts-var-button-primary-color": "#ffffff",
      "--ts-var-focus-outline-offset": "2px",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-button--secondary-color": "#333333",
      "--ts-var-input-placeholder-color": "#999999",
      "--ts-var-button--secondary-border": "#cccccc",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-button-primary-background": "#ff5a5f",
      "--ts-var-card-highlight-background": "#f9f9f9",
      "--ts-var-spotter-prompt-background": "#f7f7f7",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#e0e0e0",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#f0f0f0",
      "--ts-var-button--secondary-background": "#f7f7f7",
      "--ts-var-button--secondary-text-color": "#333333",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button-primary-hover-background": "#ff4d4f",
      "--ts-var-button-primary-active-background": "#ff3f41",
      "--ts-var-button--secondary-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-text-hover-color": "#000000",
      "--ts-var-button--secondary-active-background": "#d0d0d0",
      "--ts-var-button--secondary-text-active-color": "#000000"
    }
  }
};
            export default appConfig;