const appConfig: any = {
  "liveboardId": "e49cf23d-e977-49c3-8922-696abf904323",
  "modelId": "d797a01d-c4c7-48da-b3b5-9751a0ee4c90",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1759992715,
  "app_config": {
    "menu_items": [
      "Dashboard",
      "Analytics",
      "Products",
      "Orders",
      "Customers",
      "Settings"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#ffffff",
      "--ts-var-info-color": "#2196f3",
      "--ts-var-link-color": "#1a365d",
      "--ts-var-root-color": "#343a40",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "1px solid #dee2e6",
      "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-error-color": "#f44336",
      "--ts-var-input-color": "#495057",
      "--ts-var-menu-border": "1px solid #dee2e6",
      "--ts-var-input-border": "1px solid #ced4da",
      "--ts-var-modal-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-table-border": "1px solid #dee2e6",
      "--ts-var-spacing-large": "16px",
      "--ts-var-spacing-small": "4px",
      "--ts-var-success-color": "#4caf50",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-warning-color": "#ff9800",
      "--ts-var-disabled-color": "#6c757d",
      "--ts-var-font-size-base": "16px",
      "--ts-var-nav-background": "#1a365d",
      "--ts-var-spacing-medium": "8px",
      "--ts-var-viz-background": "#f8f9fa",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#343a40",
      "--ts-var-nav-hover-color": "#4caf50",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#1a365d",
      "--ts-var-badge-background": "#4caf50",
      "--ts-var-box-shadow-large": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-box-shadow-small": "0 1px 2px rgba(0, 0, 0, 0.1)",
      "--ts-var-font-family-base": "'Helvetica Neue', Arial, sans-serif",
      "--ts-var-font-weight-bold": "700",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-link-hover-color": "#4caf50",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-box-shadow-medium": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-heading-font-size": "24px",
      "--ts-var-link-active-color": "#388e3c",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-font-weight-normal": "400",
      "--ts-var-input-focus-border": "#4caf50",
      "--ts-var-table-cell-padding": "12px 15px",
      "--ts-var-table-header-color": "#495057",
      "--ts-var-tooltip-background": "#343a40",
      "--ts-var-tooltip-box-shadow": "0 1px 3px rgba(0, 0, 0, 0.2)",
      "--ts-var-border-radius-large": "12px",
      "--ts-var-border-radius-small": "4px",
      "--ts-var-heading-font-family": "'Helvetica Neue', Arial, sans-serif",
      "--ts-var-heading-font-weight": "700",
      "--ts-var-border-radius-medium": "8px",
      "--ts-var-table-row-background": "#ffffff",
      "--ts-var-tooltip-border-radius": "4px",
      "--ts-var-viz-description-color": "#6c757d",
      "--ts-var-viz-title-font-family": "'Helvetica Neue', Arial, sans-serif",
      "--ts-var-input-focus-box-shadow": "0 0 0 0.2rem rgba(76, 175, 80, 0.25)",
      "--ts-var-secondary-button-color": "#ffffff",
      "--ts-var-input-placeholder-color": "#adb5bd",
      "--ts-var-table-header-background": "#f8f9fa",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#f1f1f1",
      "--ts-var-menu-item-hover-background": "#f1f1f1",
      "--ts-var-table-row-hover-background": "#f1f1f1",
      "--ts-var-menu-item-active-background": "#e9ecef",
      "--ts-var-secondary-button-background": "#4caf50",
      "--ts-var-viz-description-font-family": "'Helvetica Neue', Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#e9ecef",
      "--ts-var-button--secondary-background": "#4caf50",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-secondary-button-disabled-color": "#6c757d",
      "--ts-var-secondary-button-hover-background": "#45a049",
      "--ts-var-secondary-button-disabled-background": "#c8e6c9"
    }
  }
};
            export default appConfig;