const appConfig: any = {
  "liveboardId": "2e94cc1e-8425-4b40-801f-9598e5cd7606",
  "modelId": "1d6e86e0-702e-43b2-b3fd-92b4df5ec74e",
  "host": "https://nebula-spotbuild.thoughtspotdev.cloud",
  "expires_at": 1764730006,
  "app_config": {
    "menu_items": [
      "Trips",
      "Analytics",
      "Wishlist",
      "Messages",
      "Account"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#222222",
      "--ts-var-shadow-lg": "0 8px 32px rgba(0,0,0,0.16)",
      "--ts-var-shadow-md": "0 4px 16px rgba(0,0,0,0.13)",
      "--ts-var-shadow-sm": "0 2px 8px rgba(0,0,0,0.10)",
      "--ts-var-shadow-xs": "0 1px 4px rgba(0,0,0,0.06)",
      "--ts-var-tag-color": "#ff385c",
      "--ts-var-chip-color": "#222222",
      "--ts-var-focus-ring": "0 0 0 3px #ffe7ed",
      "--ts-var-link-color": "#ff385c",
      "--ts-var-root-color": "#222222",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-chip-border": "#dddddd",
      "--ts-var-input-color": "#222222",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-avatar-color": "#222222",
      "--ts-var-footer-color": "#222222",
      "--ts-var-header-color": "#222222",
      "--ts-var-input-border": "#dddddd",
      "--ts-var-radio-border": "#dddddd",
      "--ts-var-table-border": "#dddddd",
      "--ts-var-toggle-color": "#ffffff",
      "--ts-var-divider-color": "#dddddd",
      "--ts-var-header-border": "#dddddd",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-calendar-color": "#222222",
      "--ts-var-nav-background": "#f7f7f7",
      "--ts-var-tag-background": "#ffe7ed",
      "--ts-var-tag-icon-color": "#ff385c",
      "--ts-var-viz-background": "#ffffff",
      "--ts-var-viz-box-shadow": "0 2px 8px rgba(0,0,0,0.10)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-card-box-shadow": "0 2px 8px rgba(0,0,0,0.10)",
      "--ts-var-checkbox-border": "#dddddd",
      "--ts-var-chip-background": "#ffffff",
      "--ts-var-chip-icon-color": "#ff385c",
      "--ts-var-list-item-color": "#222222",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#222222",
      "--ts-var-nav-hover-color": "#ff385c",
      "--ts-var-root-background": "#f7f7f7",
      "--ts-var-scrollbar-thumb": "#dddddd",
      "--ts-var-scrollbar-track": "#f7f7f7",
      "--ts-var-selection-color": "#ff385c",
      "--ts-var-viz-title-color": "#222222",
      "--ts-var-alert-info-color": "#222222",
      "--ts-var-badge-background": "#ff385c",
      "--ts-var-breadcrumb-color": "#222222",
      "--ts-var-card-title-color": "#222222",
      "--ts-var-chip-hover-color": "#ff385c",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-link-hover-color": "#c82344",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-radio-background": "#ffffff",
      "--ts-var-alert-error-color": "#ff385c",
      "--ts-var-avatar-background": "#dddddd",
      "--ts-var-card-header-color": "#222222",
      "--ts-var-footer-background": "#f7f7f7",
      "--ts-var-header-background": "#ffffff",
      "--ts-var-link-active-color": "#9c1c32",
      "--ts-var-toggle-background": "#dddddd",
      "--ts-var-viz-border-radius": "16px",
      "--ts-var-input-focus-border": "#ff385c",
      "--ts-var-skeleton-highlight": "#dddddd",
      "--ts-var-table-header-color": "#222222",
      "--ts-var-tooltip-background": "#222222",
      "--ts-var-alert-success-color": "#222222",
      "--ts-var-alert-warning-color": "#222222",
      "--ts-var-calendar-background": "#ffffff",
      "--ts-var-card-subtitle-color": "#717171",
      "--ts-var-checkbox-background": "#ffffff",
      "--ts-var-chip-selected-color": "#ffffff",
      "--ts-var-root-tertiary-color": "#b0b0b0",
      "--ts-var-skeleton-background": "#f0f0f0",
      "--ts-var-spotter-input-color": "#222222",
      "--ts-var-toggle-active-color": "#ffffff",
      "--ts-var-calendar-range-color": "#222222",
      "--ts-var-list-item-background": "#ffffff",
      "--ts-var-radio-checked-border": "#ff385c",
      "--ts-var-root-secondary-color": "#717171",
      "--ts-var-selection-background": "#ffe7ed",
      "--ts-var-spotter-input-border": "#dddddd",
      "--ts-var-spotter-prompt-color": "#222222",
      "--ts-var-table-row-background": "#ffffff",
      "--ts-var-alert-info-background": "#e0f4ff",
      "--ts-var-card-hover-background": "#f0f0f0",
      "--ts-var-chip-hover-background": "#ffe7ed",
      "--ts-var-pagination-item-color": "#222222",
      "--ts-var-viz-description-color": "#717171",
      "--ts-var-viz-title-font-family": "Airbnb Cereal, Nunito, Helvetica, Arial, sans-serif",
      "--ts-var-alert-error-background": "#ffe7ed",
      "--ts-var-menu-item-active-color": "#ffffff",
      "--ts-var-breadcrumb-active-color": "#ff385c",
      "--ts-var-button--secondary-color": "#222222",
      "--ts-var-calendar-selected-color": "#ffffff",
      "--ts-var-checkbox-checked-border": "#ff385c",
      "--ts-var-progress-bar-background": "#dddddd",
      "--ts-var-table-header-background": "#f7f7f7",
      "--ts-var-alert-success-background": "#d1fae5",
      "--ts-var-alert-warning-background": "#fff4e5",
      "--ts-var-chip-selected-background": "#ff385c",
      "--ts-var-modal-overlay-background": "rgba(34,34,34,0.60)",
      "--ts-var-radio-checked-background": "#ff385c",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-table-row-alt-background": "#f7f7f7",
      "--ts-var-toggle-active-background": "#ff385c",
      "--ts-var-viz-title-text-transform": "none",
      "--ts-var-calendar-range-background": "#ffe7ed",
      "--ts-var-spotter-prompt-background": "#f7f7f7",
      "--ts-var-list-item-hover-background": "#ffe7ed",
      "--ts-var-menu-item-hover-background": "#ffe7ed",
      "--ts-var-pagination-item-background": "#ffffff",
      "--ts-var-spotter-input-focus-border": "#ff385c",
      "--ts-var-table-row-hover-background": "#ffe7ed",
      "--ts-var-checkbox-checked-background": "#ff385c",
      "--ts-var-menu-item-active-background": "#ff385c",
      "--ts-var-viz-description-font-family": "Airbnb Cereal, Nunito, Helvetica, Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#ffe7ed",
      "--ts-var-button--secondary-background": "#ffffff",
      "--ts-var-calendar-selected-background": "#ff385c",
      "--ts-var-pagination-item-active-color": "#ffffff",
      "--ts-var-progress-bar-fill-background": "#ff385c",
      "--ts-var-button--secondary-hover-color": "#ff385c",
      "--ts-var-button--secondary-active-color": "#c82344",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-spotter-input-placeholder-color": "#b0b0b0",
      "--ts-var-pagination-item-hover-background": "#ffe7ed",
      "--ts-var-pagination-item-active-background": "#ff385c",
      "--ts-var-button--secondary-hover-background": "#f0f0f0",
      "--ts-var-button--secondary-active-background": "#e5e5e5"
    }
  }
};
            export default appConfig;