const appConfig: any = {
  "liveboardId": "2176845e-ff8f-4ea2-aeac-bf332d3450b4",
  "modelId": "a2277b5b-651d-4aec-be36-8401ff748780",
  "host": "https://nebula-spotbuild.thoughtspotdev.cloud",
  "expires_at": 1764714320,
  "app_config": {
    "menu_items": [
      "Trips",
      "Analytics",
      "Wishlist",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-shadow-1": "0 1.5px 4px rgba(0,0,0,0.06)",
      "--ts-var-shadow-2": "0 4px 16px rgba(0,0,0,0.09)",
      "--ts-var-nav-color": "#222222",
      "--ts-var-tag-color": "#222222",
      "--ts-var-card-color": "#222222",
      "--ts-var-chip-color": "#222222",
      "--ts-var-nav-border": "#dddddd",
      "--ts-var-pill-color": "#222222",
      "--ts-var-root-color": "#222222",
      "--ts-var-tabs-color": "#222222",
      "--ts-var-tag-border": "#dddddd",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-chip-border": "#dddddd",
      "--ts-var-input-color": "#222222",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-modal-color": "#222222",
      "--ts-var-tabs-border": "#dddddd",
      "--ts-var-avatar-color": "#222222",
      "--ts-var-header-color": "#222222",
      "--ts-var-input-border": "#dddddd",
      "--ts-var-shadow-focus": "0 0 0 2px #ff385c22",
      "--ts-var-table-border": "#dddddd",
      "--ts-var-divider-color": "#ebebeb",
      "--ts-var-header-border": "#ebebeb",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-viz-grid-line": "#ebebeb",
      "--ts-var-z-index-modal": "10000",
      "--ts-var-modal-backdrop": "rgba(34,34,34,0.38)",
      "--ts-var-nav-background": "#f7f7f7",
      "--ts-var-nav-logo-color": "#ff385c",
      "--ts-var-tabs-indicator": "#ff385c",
      "--ts-var-tag-background": "#f7f7f7",
      "--ts-var-viz-background": "#ffffff",
      "--ts-var-viz-box-shadow": "0 2px 8px rgba(0,0,0,0.05)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-card-box-shadow": "0 2px 8px rgba(0,0,0,0.05)",
      "--ts-var-chip-background": "#f7f7f7",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#222222",
      "--ts-var-nav-hover-color": "#ff385c",
      "--ts-var-pill-background": "#f7f7f7",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-root-link-color": "#ff385c",
      "--ts-var-scrollbar-thumb": "#c7c7c7",
      "--ts-var-scrollbar-track": "#f7f7f7",
      "--ts-var-tabs-background": "#ffffff",
      "--ts-var-viz-title-color": "#222222",
      "--ts-var-alert-info-color": "#222222",
      "--ts-var-badge-background": "#ff385c",
      "--ts-var-chip-hover-color": "#222222",
      "--ts-var-input-background": "#f7f7f7",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-nav-active-color": "#ff385c",
      "--ts-var-pagination-color": "#222222",
      "--ts-var-tabs-hover-color": "#222222",
      "--ts-var-z-index-dropdown": "9999",
      "--ts-var-alert-error-color": "#b00020",
      "--ts-var-avatar-background": "#f7f7f7",
      "--ts-var-header-background": "#ffffff",
      "--ts-var-stepper-connector": "#dddddd",
      "--ts-var-switch-background": "#dddddd",
      "--ts-var-tabs-active-color": "#ff385c",
      "--ts-var-viz-border-radius": "16px",
      "--ts-var-input-focus-border": "#ff385c",
      "--ts-var-skeleton-highlight": "#f7f7f7",
      "--ts-var-stepper-background": "#f7f7f7",
      "--ts-var-stepper-step-color": "#717171",
      "--ts-var-table-header-color": "#222222",
      "--ts-var-tooltip-background": "#222222",
      "--ts-var-tooltip-box-shadow": "0 2px 8px rgba(0,0,0,0.18)",
      "--ts-var-alert-success-color": "#222222",
      "--ts-var-alert-warning-color": "#b86b00",
      "--ts-var-chip-selected-color": "#ffffff",
      "--ts-var-pill-selected-color": "#ffffff",
      "--ts-var-progress-background": "#dddddd",
      "--ts-var-root-tertiary-color": "#c7c7c7",
      "--ts-var-skeleton-background": "#ebebeb",
      "--ts-var-spotter-input-color": "#222222",
      "--ts-var-input-disabled-color": "#c7c7c7",
      "--ts-var-nav-unselected-color": "#717171",
      "--ts-var-root-secondary-color": "#717171",
      "--ts-var-spotter-input-border": "#dddddd",
      "--ts-var-spotter-prompt-color": "#222222",
      "--ts-var-alert-info-background": "#f7f7f7",
      "--ts-var-chip-hover-background": "#ebebeb",
      "--ts-var-menu-item-hover-color": "#222222",
      "--ts-var-pagination-background": "#ffffff",
      "--ts-var-root-link-hover-color": "#d82e52",
      "--ts-var-spotter-prompt-border": "#dddddd",
      "--ts-var-viz-description-color": "#717171",
      "--ts-var-viz-title-font-family": "Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif",
      "--ts-var-alert-error-background": "#fff2f2",
      "--ts-var-button--tertiary-color": "#222222",
      "--ts-var-menu-item-active-color": "#ffffff",
      "--ts-var-pagination-hover-color": "#222222",
      "--ts-var-slider-rail-background": "#dddddd",
      "--ts-var-table-row-active-color": "#ffffff",
      "--ts-var-button--secondary-color": "#222222",
      "--ts-var-button--tertiary-border": "transparent",
      "--ts-var-input-placeholder-color": "#717171",
      "--ts-var-nav-selected-background": "#f7f7f7",
      "--ts-var-pagination-active-color": "#ffffff",
      "--ts-var-progress-bar-background": "#ff385c",
      "--ts-var-slider-thumb-background": "#ffffff",
      "--ts-var-slider-track-background": "#ff385c",
      "--ts-var-switch-thumb-background": "#ffffff",
      "--ts-var-table-header-background": "#f7f7f7",
      "--ts-var-alert-success-background": "#f7f7f7",
      "--ts-var-alert-warning-background": "#fff7e6",
      "--ts-var-button--secondary-border": "#dddddd",
      "--ts-var-chip-selected-background": "#ff385c",
      "--ts-var-pill-selected-background": "#ff385c",
      "--ts-var-spotter-input-background": "#f7f7f7",
      "--ts-var-viz-title-text-transform": "none",
      "--ts-var-input-disabled-background": "#ebebeb",
      "--ts-var-spotter-prompt-background": "#ffffff",
      "--ts-var-stepper-step-active-color": "#ff385c",
      "--ts-var-switch-checked-background": "#ff385c",
      "--ts-var-menu-item-hover-background": "#f7f7f7",
      "--ts-var-table-row-hover-background": "#f7f7f7",
      "--ts-var-button--tertiary-background": "#f7f7f7",
      "--ts-var-menu-item-active-background": "#ff385c",
      "--ts-var-pagination-hover-background": "#f7f7f7",
      "--ts-var-table-row-active-background": "#ff385c",
      "--ts-var-viz-description-font-family": "Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif",
      "--ts-var-viz-legend-hover-background": "#f7f7f7",
      "--ts-var-button--secondary-background": "#ffffff",
      "--ts-var-button--tertiary-hover-color": "#222222",
      "--ts-var-pagination-active-background": "#ff385c",
      "--ts-var-button--secondary-hover-color": "#222222",
      "--ts-var-button--secondary-hover-border": "#c7c7c7",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-spotter-input-placeholder-color": "#717171",
      "--ts-var-spotter-prompt-placeholder-color": "#717171",
      "--ts-var-button--tertiary-hover-background": "#ebebeb",
      "--ts-var-button--secondary-hover-background": "#f7f7f7"
    }
  }
};
            export default appConfig;