const appConfig: any = {
  "liveboardId": "0ed25f68-7630-4d7a-9bec-869be5056873",
  "modelId": "f2663039-0de6-4f07-882a-885fdd6f4aa9",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758189333,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-root-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-viz-background": "#f7f7f7",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-menu-item-border": "#dddddd",
      "--ts-var-viz-border-color": "#dddddd",
      "--ts-var-viz-legend-color": "#333333",
      "--ts-var-viz-title-weight": "bold",
      "--ts-var-menu-item-opacity": "1",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-viz-legend-border": "#dddddd",
      "--ts-var-viz-title-opacity": "1",
      "--ts-var-menu-border-radius": "4px",
      "--ts-var-viz-border-opacity": "1",
      "--ts-var-viz-legend-opacity": "1",
      "--ts-var-spotter-input-color": "#333333",
      "--ts-var-viz-title-font-size": "16px",
      "--ts-var-spotter-prompt-color": "#666666",
      "--ts-var-menu-item-hover-color": "#333333",
      "--ts-var-spotter-input-opacity": "1",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-legend-background": "#ffffff",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-viz-title-hover-color": "#ff5a5f",
      "--ts-var-viz-title-line-height": "1.5",
      "--ts-var-menu-item-active-color": "#ffffff",
      "--ts-var-spotter-prompt-opacity": "0.8",
      "--ts-var-viz-background-opacity": "0.9",
      "--ts-var-viz-description-weight": "normal",
      "--ts-var-viz-title-active-color": "#ff5a5f",
      "--ts-var-button--secondary-color": "#ffffff",
      "--ts-var-menu-item-hover-opacity": "1",
      "--ts-var-viz-description-opacity": "0.8",
      "--ts-var-menu-item-active-opacity": "1",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-legend-hover-opacity": "1",
      "--ts-var-viz-title-letter-spacing": "0.5px",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-button--secondary-opacity": "1",
      "--ts-var-button--secondary-padding": "10px 15px",
      "--ts-var-spotter-prompt-background": "#f7f7f7",
      "--ts-var-viz-description-font-size": "14px",
      "--ts-var-viz-legend-active-opacity": "1",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-button--secondary-font-size": "14px",
      "--ts-var-menu-item-active-background": "#ff5a5f",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-description-hover-color": "#666666",
      "--ts-var-viz-description-line-height": "1.5",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#ff5a5f",
      "--ts-var-viz-description-active-color": "#333333",
      "--ts-var-button--secondary-font-weight": "bold",
      "--ts-var-button--secondary-hover-color": "#ffffff",
      "--ts-var-button--secondary-active-color": "#ffffff",
      "--ts-var-viz-description-letter-spacing": "0.5px",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-border-radius": "4px",
      "--ts-var-button--secondary-hover-opacity": "1",
      "--ts-var-button--secondary-active-opacity": "1",
      "--ts-var-button--secondary-hover-background": "#e04e54",
      "--ts-var-button--secondary-active-background": "#d94349"
    }
  }
};
            export default appConfig;