const appConfig: any = {
  "liveboardId": "bce501d5-7f7c-483d-8056-e1751c72545b",
  "modelId": "68855e62-e9b2-4c3b-b5c1-65c2ac9df1fd",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757661329,
  "color_schema": {
    "--ts-var-root-color": "#333333",
    "--ts-var-viz-border": "#dddddd",
    "--ts-var-menu-border": "#dddddd",
    "--ts-var-viz-background": "#f2f2f2",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#333333",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#333333",
    "--ts-var-viz-border-hover": "#cccccc",
    "--ts-var-viz-border-active": "#bbbbbb",
    "--ts-var-viz-border-radius": "4px",
    "--ts-var-spotter-input-color": "#333333",
    "--ts-var-menu-item-background": "#ffffff",
    "--ts-var-root-secondary-color": "#666666",
    "--ts-var-spotter-input-border": "#cccccc",
    "--ts-var-spotter-prompt-color": "#333333",
    "--ts-var-viz-background-hover": "#eaeaea",
    "--ts-var-viz-title-background": "#ffffff",
    "--ts-var-menu-item-hover-color": "#333333",
    "--ts-var-viz-background-active": "#e0e0e0",
    "--ts-var-viz-description-color": "#666666",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-viz-title-hover-color": "#000000",
    "--ts-var-menu-item-active-color": "#ffffff",
    "--ts-var-menu-item-hover-border": "#f6eb61",
    "--ts-var-viz-title-active-color": "#000000",
    "--ts-var-button--secondary-color": "#333333",
    "--ts-var-menu-item-active-border": "#f6eb61",
    "--ts-var-button--secondary-border": "#dddddd",
    "--ts-var-spotter-input-background": "#f9f9f9",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#ffffff",
    "--ts-var-menu-item-hover-background": "#f6eb61",
    "--ts-var-spotter-input-hover-border": "#aaaaaa",
    "--ts-var-viz-description-background": "#ffffff",
    "--ts-var-viz-title-hover-background": "#f9f9f9",
    "--ts-var-menu-item-active-background": "#f6eb61",
    "--ts-var-spotter-input-active-border": "#888888",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-description-hover-color": "#444444",
    "--ts-var-viz-legend-hover-background": "#e0e0e0",
    "--ts-var-viz-title-active-background": "#f2f2f2",
    "--ts-var-button--secondary-background": "#f6eb61",
    "--ts-var-button--secondary-box-shadow": "0 1px 2px rgba(0, 0, 0, 0.1)",
    "--ts-var-button--secondary-text-color": "#333333",
    "--ts-var-viz-description-active-color": "#444444",
    "--ts-var-button--secondary-hover-color": "#333333",
    "--ts-var-button--secondary-active-color": "#333333",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-active-border": "#dddddd",
    "--ts-var-button--secondary-border-radius": "4px",
    "--ts-var-viz-description-hover-background": "#f9f9f9",
    "--ts-var-viz-description-active-background": "#f2f2f2",
    "--ts-var-button--secondary-hover-background": "#e0e0e0",
    "--ts-var-button--secondary-active-background": "#d0d0d0"
  }
};
            export default appConfig;