const appConfig: any = {
  "liveboardId": "125dbd64-3cb2-42d3-8fc9-b9dcf268be6c",
  "modelId": "92c692c1-0ba9-416c-9b1c-cd7607d3ffea",
  "host": "https://nebula-spotbuild.thoughtspotdev.cloud",
  "expires_at": 1764701327,
  "app_config": {
    "menu_items": [
      "Trips",
      "Analytics",
      "Wishlist",
      "Messages",
      "Account"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#222222",
      "--ts-var-card-color": "#222222",
      "--ts-var-chip-color": "#222222",
      "--ts-var-link-color": "#222222",
      "--ts-var-root-color": "#222222",
      "--ts-var-viz-border": "#e0e0e0",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "#e0e0e0",
      "--ts-var-chip-border": "#e0e0e0",
      "--ts-var-input-color": "#222222",
      "--ts-var-menu-border": "#e0e0e0",
      "--ts-var-modal-color": "#222222",
      "--ts-var-toast-color": "#ffffff",
      "--ts-var-avatar-color": "#ffffff",
      "--ts-var-filter-color": "#ff385c",
      "--ts-var-footer-color": "#717171",
      "--ts-var-header-color": "#222222",
      "--ts-var-input-border": "#e0e0e0",
      "--ts-var-modal-border": "#e0e0e0",
      "--ts-var-divider-color": "#e0e0e0",
      "--ts-var-header-border": "#e0e0e0",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-dropdown-color": "#222222",
      "--ts-var-nav-background": "#ffffff",
      "--ts-var-progress-color": "#ff385c",
      "--ts-var-snackbar-color": "#ffffff",
      "--ts-var-viz-background": "#ffffff",
      "--ts-var-viz-box-shadow": "0 2px 16px 0 rgba(0,0,0,.08)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-card-box-shadow": "0 2px 16px 0 rgba(0,0,0,.08)",
      "--ts-var-chip-background": "#ffffff",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#222222",
      "--ts-var-nav-hover-color": "#ff385c",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-scrollbar-thumb": "#e0e0e0",
      "--ts-var-scrollbar-track": "#ffffff",
      "--ts-var-viz-title-color": "#222222",
      "--ts-var-badge-background": "#ff385c",
      "--ts-var-input-background": "#f7f7f7",
      "--ts-var-link-hover-color": "#ff385c",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-table-background": "#ffffff",
      "--ts-var-toast-background": "#222222",
      "--ts-var-viz-legend-color": "#222222",
      "--ts-var-avatar-background": "#ff385c",
      "--ts-var-chip-active-color": "#ffffff",
      "--ts-var-filter-background": "#ffffff",
      "--ts-var-footer-background": "#f7f7f7",
      "--ts-var-header-background": "#ffffff",
      "--ts-var-link-active-color": "#c81d4e",
      "--ts-var-root-border-color": "#e0e0e0",
      "--ts-var-search-background": "#ffffff",
      "--ts-var-search-icon-color": "#ffffff",
      "--ts-var-viz-border-radius": "18px",
      "--ts-var-card-border-radius": "18px",
      "--ts-var-input-border-focus": "#ff385c",
      "--ts-var-search-input-color": "#222222",
      "--ts-var-table-header-color": "#222222",
      "--ts-var-tooltip-background": "#222222",
      "--ts-var-dropdown-background": "#ffffff",
      "--ts-var-filter-active-color": "#ffffff",
      "--ts-var-progress-background": "#e0e0e0",
      "--ts-var-root-tertiary-color": "#b0b0b0",
      "--ts-var-snackbar-background": "#222222",
      "--ts-var-spotter-input-color": "#222222",
      "--ts-var-root-secondary-color": "#717171",
      "--ts-var-spotter-prompt-color": "#717171",
      "--ts-var-chip-hover-background": "#ffe6ec",
      "--ts-var-viz-description-color": "#717171",
      "--ts-var-viz-header-background": "#ffffff",
      "--ts-var-viz-legend-background": "#f7f7f7",
      "--ts-var-viz-title-font-family": "Airbnb Cereal, Helvetica, Arial, sans-serif",
      "--ts-var-chip-active-background": "#ff385c",
      "--ts-var-search-icon-background": "#ff385c",
      "--ts-var-button--secondary-color": "#222222",
      "--ts-var-root-border-hover-color": "#d4d4d4",
      "--ts-var-search-input-background": "#f7f7f7",
      "--ts-var-table-header-background": "#f7f7f7",
      "--ts-var-button--secondary-border": "#e0e0e0",
      "--ts-var-filter-active-background": "#ff385c",
      "--ts-var-root-border-active-color": "#cccccc",
      "--ts-var-spotter-input-background": "#f7f7f7",
      "--ts-var-viz-title-text-transform": "none",
      "--ts-var-dropdown-hover-background": "#f7f7f7",
      "--ts-var-spotter-prompt-background": "#ffffff",
      "--ts-var-dropdown-active-background": "#ffe6ec",
      "--ts-var-menu-item-hover-background": "#f7f7f7",
      "--ts-var-table-row-hover-background": "#ffe6ec",
      "--ts-var-menu-item-active-background": "#ffe6ec",
      "--ts-var-table-row-active-background": "#ffe6ec",
      "--ts-var-viz-description-font-family": "Airbnb Cereal, Helvetica, Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#ffe6ec",
      "--ts-var-button--secondary-background": "#f7f7f7",
      "--ts-var-search-icon-hover-background": "#c81d4e",
      "--ts-var-button--secondary-border-hover": "#d4d4d4",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-border-active": "#cccccc",
      "--ts-var-button--secondary-hover-background": "#ececec",
      "--ts-var-button--secondary-active-background": "#e0e0e0"
    }
  }
};
            export default appConfig;