const appConfig: any = {
  "liveboardId": "f1bd8da5-033b-424f-b95b-1aba2e1eb799",
  "modelId": "ef58538c-e3dc-40cb-a9fe-6f87adb004ac",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758198770,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-body-color": "#666666",
      "--ts-var-link-color": "#ff5a5f",
      "--ts-var-root-color": "#333333",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-card-shadow": "0 1px 3px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-input-border": "#dddddd",
      "--ts-var-shadow-large": "0 4px 8px rgba(0, 0, 0, 0.1)",
      "--ts-var-shadow-small": "0 1px 2px rgba(0, 0, 0, 0.1)",
      "--ts-var-spinner-size": "24px",
      "--ts-var-badge-padding": "4px 8px",
      "--ts-var-divider-color": "#dddddd",
      "--ts-var-heading-color": "#333333",
      "--ts-var-shadow-medium": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-spacing-large": "24px",
      "--ts-var-spacing-small": "8px",
      "--ts-var-spinner-color": "#ff5a5f",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-body-font-size": "14px",
      "--ts-var-spacing-medium": "16px",
      "--ts-var-spinner-border": "#dddddd",
      "--ts-var-toggle-padding": "4px",
      "--ts-var-tooltip-border": "#ff5a5f",
      "--ts-var-viz-background": "#f7f7f7",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-badge-background": "#ff5a5f",
      "--ts-var-body-font-family": "Arial, sans-serif",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-link-hover-color": "#ff4c4f",
      "--ts-var-card-hover-shadow": "0 2px 5px rgba(0, 0, 0, 0.15)",
      "--ts-var-divider-thickness": "1px",
      "--ts-var-link-active-color": "#ff3f3f",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-card-active-shadow": "0 0 0 4px rgba(255, 90, 95, 0.5)",
      "--ts-var-input-error-border": "#ff4c4f",
      "--ts-var-input-focus-border": "#ff5a5f",
      "--ts-var-spinner-background": "#ffffff",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-badge-border-radius": "12px",
      "--ts-var-border-radius-large": "12px",
      "--ts-var-border-radius-small": "4px",
      "--ts-var-heading-font-family": "Arial, sans-serif",
      "--ts-var-heading-font-weight": "bold",
      "--ts-var-toggle-thumb-border": "#dddddd",
      "--ts-var-border-radius-medium": "8px",
      "--ts-var-toggle-border-radius": "12px",
      "--ts-var-toggle-on-background": "#ff5a5f",
      "--ts-var-toggle-off-background": "#cccccc",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-button--secondary-color": "#ffffff",
      "--ts-var-input-placeholder-color": "#aaaaaa",
      "--ts-var-toggle-thumb-background": "#ffffff",
      "--ts-var-spotter-input-background": "#f0f0f0",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-spotter-prompt-background": "#ffffff",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#ff5a5f",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#ff5a5f",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-disabled-color": "#666666",
      "--ts-var-button--secondary-hover-background": "#ff4c4f",
      "--ts-var-button--secondary-active-background": "#ff3f3f",
      "--ts-var-button--secondary-disabled-background": "#cccccc"
    }
  }
};
            export default appConfig;