const appConfig: any = {
  "liveboardId": "9ef186de-2e6b-48e1-8b7b-ad30cd46bf32",
  "modelId": "3bfa218c-1511-4d05-996e-9bb688e14a9c",
  "host": "https://growth.thoughtspot.cloud",
  "expires_at": 1763359189,
  "app_config": {
    "menu_items": [
      "Home",
      "Analytics",
      "Orders",
      "Products",
      "Customers",
      "Online Store"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#FFFFFF",
      "--ts-var-kpi-hero-color": "#212326",
      "--ts-var-nav-background": "#008060",
      "--ts-var-nav-hover-color": "#D0F5E0",
      "--ts-var-viz-title-color": "#212326",
      "--ts-var-axis-title-color": "#5E6D55",
      "--ts-var-kpi-comparison-color": "#5E6D55",
      "--ts-var-liveboard-chip-color": "#212326",
      "--ts-var-axis-data-label-color": "#5E6D55",
      "--ts-var-viz-description-color": "#5E6D55",
      "--ts-var-kpi-analyze-text-color": "#008060",
      "--ts-var-liveboard-bg-dot-color": "#B2D97C",
      "--ts-var-chart-legend-text-color": "#5E6D55",
      "--ts-var-liveboard-chip-background": "#C5E1A5",
      "--ts-var-liveboard-tile-background": "#E3F3D4",
      "--ts-var-parameter-chip-background": "#5E6D55",
      "--ts-var-parameter-chip-text-color": "#FFFFFF",
      "--ts-var-liveboard-group-background": "#E3F3D4",
      "--ts-var-kpi-hero-color--highlighted": "#E3F3D4",
      "--ts-var-liveboard-chip--hover-color": "#212326",
      "--ts-var-liveboard-header-background": "#E3F3D4",
      "--ts-var-liveboard-header-font-color": "#212326",
      "--ts-var-liveboard-layout-background": "#95BF47",
      "--ts-var-liveboard-tile-border-color": "#7CA13A",
      "--ts-var-viz-background--highlighted": "#212326",
      "--ts-var-viz-legend-hover-background": "#D0EACB",
      "--ts-var-liveboard-chip--active-color": "#212326",
      "--ts-var-liveboard-group-border-color": "#7CA13A",
      "--ts-var-viz-title-color--highlighted": "#E3F3D4",
      "--ts-var-axis-title-color--highlighted": "#E3F3D4",
      "--ts-var-viz-border-color--highlighted": "#3A4B2F",
      "--ts-var-kpi-delta-badge-negative-color": "#D72C0D",
      "--ts-var-kpi-delta-badge-positive-color": "#008060",
      "--ts-var-liveboard-group-tile-background": "#E3F3D4",
      "--ts-var-parameter-chip-hover-background": "#3A4B2F",
      "--ts-var-parameter-chip-hover-text-color": "#FFFFFF",
      "--ts-var-liveboard-chip--hover-background": "#A2C46A",
      "--ts-var-liveboard-group-title-font-color": "#212326",
      "--ts-var-parameter-chip-active-background": "#212326",
      "--ts-var-parameter-chip-active-text-color": "#FFFFFF",
      "--ts-var-kpi-comparison-color--highlighted": "#B2D97C",
      "--ts-var-liveboard-chip--active-background": "#7CA13A",
      "--ts-var-liveboard-group-tile-border-color": "#7CA13A",
      "--ts-var-liveboard-header-badge-background": "#008060",
      "--ts-var-liveboard-header-badge-font-color": "#FFFFFF",
      "--ts-var-liveboard-tab-active-border-color": "#008060",
      "--ts-var-axis-data-label-color--highlighted": "#E3F3D4",
      "--ts-var-liveboard-header-badge-hover-color": "#00664D",
      "--ts-var-viz-description-color--highlighted": "#B2D97C",
      "--ts-var-kpi-analyze-text-color--highlighted": "#34C98F",
      "--ts-var-kpi-delta-badge-negative-background": "#FBEAE5",
      "--ts-var-kpi-delta-badge-positive-background": "#D0F5E0",
      "--ts-var-liveboard-header-badge-active-color": "#004D3A",
      "--ts-var-liveboard-notetitle-body-font-color": "#212326",
      "--ts-var-chart-legend-text-color--highlighted": "#E3F3D4",
      "--ts-var-liveboard-group-tile-title-font-color": "#212326",
      "--ts-var-liveboard-group-description-font-color": "#5E6D55",
      "--ts-var-liveboard-notetitle-heading-font-color": "#212326",
      "--ts-var-viz-legend-hover-background--highlighted": "#212326",
      "--ts-var-liveboard-header-action-button-background": "#C5E1A5",
      "--ts-var-liveboard-header-action-button-font-color": "#212326",
      "--ts-var-liveboard-header-action-button-hover-color": "#A2C46A",
      "--ts-var-liveboard-header-badge-modified-background": "#5E6D55",
      "--ts-var-kpi-delta-badge-negative-color--highlighted": "#E3F3D4",
      "--ts-var-kpi-delta-badge-positive-color--highlighted": "#E3F3D4",
      "--ts-var-liveboard-group-tile-description-font-color": "#5E6D55",
      "--ts-var-liveboard-header-action-button-active-color": "#7CA13A",
      "--ts-var-kpi-delta-badge-negative-background--highlighted": "#D72C0D",
      "--ts-var-kpi-delta-badge-positive-background--highlighted": "#008060",
      "--ts-var-liveboard-notetitle-body-font-color--highlighted": "#C5E1A5",
      "--ts-var-liveboard-notetitle-heading-font-color--highlighted": "#E3F3D4",
      "--ts-var-liveboard-header-action-button-background--highlighted": "#5E6D55",
      "--ts-var-liveboard-header-action-button-font-color--highlighted": "#FFFFFF",
      "--ts-var-liveboard-header-action-button-hover-color--highlighted": "#3A4B2F",
      "--ts-var-liveboard-header-action-button-active-color--highlighted": "#212326"
    }
  }
};
            export default appConfig;