const appConfig: any = {
  "liveboardId": "9875568c-3145-44c2-be59-ebccdde6c2a2",
  "modelId": "da3cfaa5-310e-421e-b8dd-877e6e845911",
  "host": "https://nebula-spotbuild.thoughtspotdev.cloud",
  "expires_at": 1764716584,
  "app_config": {
    "menu_items": [
      "Home",
      "Analytics",
      "Trips",
      "Wishlist",
      "Messages",
      "Account"
    ],
    "color_schema": {
      "--ts-var-nav-color": "#222222",
      "--ts-var-tag-color": "#222222",
      "--ts-var-chip-color": "#222222",
      "--ts-var-icon-color": "#717171",
      "--ts-var-link-color": "#ff385c",
      "--ts-var-pill-color": "#222222",
      "--ts-var-root-color": "#222222",
      "--ts-var-badge-color": "#ffffff",
      "--ts-var-card-border": "#ebebeb",
      "--ts-var-card-shadow": "0 2px 12px rgba(0,0,0,0.06)",
      "--ts-var-input-color": "#222222",
      "--ts-var-menu-border": "#ebebeb",
      "--ts-var-nav-divider": "#ebebeb",
      "--ts-var-toast-color": "#ffffff",
      "--ts-var-avatar-color": "#222222",
      "--ts-var-footer-color": "#717171",
      "--ts-var-header-color": "#222222",
      "--ts-var-input-border": "#ebebeb",
      "--ts-var-modal-border": "#ebebeb",
      "--ts-var-navbar-color": "#222222",
      "--ts-var-radio-border": "#b0b0b0",
      "--ts-var-root-divider": "#ebebeb",
      "--ts-var-table-border": "#ebebeb",
      "--ts-var-dialog-border": "#ebebeb",
      "--ts-var-drawer-border": "#ebebeb",
      "--ts-var-footer-border": "#ebebeb",
      "--ts-var-header-border": "#ebebeb",
      "--ts-var-navbar-border": "#ebebeb",
      "--ts-var-navbar-shadow": "0 2px 8px rgba(0,0,0,0.03)",
      "--ts-var-popover-color": "#222222",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-menu-separator": "#ebebeb",
      "--ts-var-nav-background": "#f7f7f7",
      "--ts-var-nav-icon-color": "#717171",
      "--ts-var-popover-border": "#ebebeb",
      "--ts-var-popover-shadow": "0 2px 8px rgba(0,0,0,0.06)",
      "--ts-var-tag-background": "#f7f7f7",
      "--ts-var-tooltip-border": "#ebebeb",
      "--ts-var-tooltip-shadow": "0 2px 8px rgba(0,0,0,0.10)",
      "--ts-var-viz-background": "#ffffff",
      "--ts-var-viz-box-shadow": "0 2px 16px rgba(0,0,0,0.06)",
      "--ts-var-calendar-border": "#ebebeb",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-checkbox-border": "#b0b0b0",
      "--ts-var-chip-background": "#f7f7f7",
      "--ts-var-dropdown-border": "#ebebeb",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#222222",
      "--ts-var-nav-hover-color": "#ff385c",
      "--ts-var-pill-background": "#f7f7f7",
      "--ts-var-radio-dot-color": "#ff385c",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-root-link-color": "#ff385c",
      "--ts-var-scrollbar-thumb": "#ebebeb",
      "--ts-var-scrollbar-track": "#f7f7f7",
      "--ts-var-viz-title-color": "#222222",
      "--ts-var-badge-background": "#ff385c",
      "--ts-var-card-title-color": "#222222",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-link-hover-color": "#d62950",
      "--ts-var-modal-background": "#ffffff",
      "--ts-var-nav-active-color": "#ff385c",
      "--ts-var-pagination-color": "#222222",
      "--ts-var-radio-background": "#ffffff",
      "--ts-var-toast-background": "#222222",
      "--ts-var-toast-info-color": "#ffffff",
      "--ts-var-viz-legend-color": "#717171",
      "--ts-var-avatar-background": "#ececec",
      "--ts-var-dialog-background": "#ffffff",
      "--ts-var-drawer-background": "#ffffff",
      "--ts-var-footer-background": "#f7f7f7",
      "--ts-var-header-background": "#ffffff",
      "--ts-var-header-link-color": "#ff385c",
      "--ts-var-icon-active-color": "#ff385c",
      "--ts-var-modal-close-color": "#b0b0b0",
      "--ts-var-modal-title-color": "#222222",
      "--ts-var-navbar-background": "#ffffff",
      "--ts-var-pagination-border": "#ebebeb",
      "--ts-var-root-border-color": "#ebebeb",
      "--ts-var-status-info-color": "#017aff",
      "--ts-var-switch-background": "#b0b0b0",
      "--ts-var-toast-error-color": "#ffffff",
      "--ts-var-viz-border-radius": "16px",
      "--ts-var-dialog-close-color": "#b0b0b0",
      "--ts-var-dialog-title-color": "#222222",
      "--ts-var-header-title-color": "#222222",
      "--ts-var-input-focus-border": "#ff385c",
      "--ts-var-link-visited-color": "#9e1b31",
      "--ts-var-popover-background": "#ffffff",
      "--ts-var-status-error-color": "#ff385c",
      "--ts-var-table-footer-color": "#717171",
      "--ts-var-table-header-color": "#222222",
      "--ts-var-tag-selected-color": "#ffffff",
      "--ts-var-tooltip-background": "#222222",
      "--ts-var-calendar-background": "#ffffff",
      "--ts-var-calendar-cell-color": "#222222",
      "--ts-var-checkbox-background": "#ffffff",
      "--ts-var-chip-selected-color": "#ffffff",
      "--ts-var-drawer-header-color": "#222222",
      "--ts-var-dropdown-background": "#ffffff",
      "--ts-var-dropdown-item-color": "#222222",
      "--ts-var-link-disabled-color": "#b0b0b0",
      "--ts-var-navbar-active-color": "#ff385c",
      "--ts-var-pill-selected-color": "#ffffff",
      "--ts-var-root-tertiary-color": "#b0b0b0",
      "--ts-var-spotter-input-color": "#222222",
      "--ts-var-toast-success-color": "#ffffff",
      "--ts-var-checkbox-check-color": "#ff385c",
      "--ts-var-dialog-content-color": "#222222",
      "--ts-var-root-secondary-color": "#717171",
      "--ts-var-spotter-input-border": "#ebebeb",
      "--ts-var-status-success-color": "#34a853",
      "--ts-var-status-warning-color": "#ffad1f",
      "--ts-var-table-row-background": "#ffffff",
      "--ts-var-loading-spinner-color": "#ff385c",
      "--ts-var-nav-active-background": "#ffebf0",
      "--ts-var-nav-icon-active-color": "#ff385c",
      "--ts-var-pagination-background": "#f7f7f7",
      "--ts-var-root-link-hover-color": "#d62950",
      "--ts-var-toast-info-background": "#017aff",
      "--ts-var-viz-description-color": "#717171",
      "--ts-var-viz-title-font-family": "Airbnb Cereal, system-ui, sans-serif",
      "--ts-var-status-info-background": "#eaf4ff",
      "--ts-var-toast-error-background": "#ff385c",
      "--ts-var-button--secondary-color": "#222222",
      "--ts-var-input-placeholder-color": "#b0b0b0",
      "--ts-var-navbar-hover-background": "#f7f7f7",
      "--ts-var-pagination-active-color": "#ffffff",
      "--ts-var-status-error-background": "#fff2f6",
      "--ts-var-table-footer-background": "#f7f7f7",
      "--ts-var-table-header-background": "#f7f7f7",
      "--ts-var-tag-selected-background": "#ff385c",
      "--ts-var-chip-selected-background": "#ff385c",
      "--ts-var-modal-overlay-background": "rgba(34,34,34,0.3)",
      "--ts-var-navbar-active-background": "#ffebf0",
      "--ts-var-pill-selected-background": "#ff385c",
      "--ts-var-spotter-input-background": "#f7f7f7",
      "--ts-var-switch-slider-background": "#ffffff",
      "--ts-var-table-row-selected-color": "#222222",
      "--ts-var-toast-success-background": "#34a853",
      "--ts-var-viz-title-text-transform": "none",
      "--ts-var-spotter-prompt-background": "#ffffff",
      "--ts-var-spotter-search-icon-color": "#ffffff",
      "--ts-var-status-success-background": "#e7f5e7",
      "--ts-var-status-warning-background": "#fff2df",
      "--ts-var-switch-checked-background": "#ff385c",
      "--ts-var-viz-legend-selected-color": "#ff385c",
      "--ts-var-calendar-header-background": "#f7f7f7",
      "--ts-var-menu-item-hover-background": "#ececec",
      "--ts-var-table-row-hover-background": "#f7f7f7",
      "--ts-var-menu-item-active-background": "#e0e0e0",
      "--ts-var-viz-description-font-family": "Airbnb Cereal, system-ui, sans-serif",
      "--ts-var-viz-legend-hover-background": "#f7f7f7",
      "--ts-var-button--secondary-background": "#f7f7f7",
      "--ts-var-calendar-cell-selected-color": "#ffffff",
      "--ts-var-pagination-active-background": "#ff385c",
      "--ts-var-button--secondary-hover-color": "#222222",
      "--ts-var-table-row-selected-background": "#ffebf0",
      "--ts-var-button--secondary-active-color": "#222222",
      "--ts-var-button--secondary-border-color": "#ebebeb",
      "--ts-var-calendar-cell-hover-background": "#ffebf0",
      "--ts-var-dropdown-item-hover-background": "#ececec",
      "--ts-var-spotter-search-icon-background": "#ff385c",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-viz-legend-selected-background": "#ffebf0",
      "--ts-var-spotter-input-placeholder-color": "#b0b0b0",
      "--ts-var-switch-slider-checked-background": "#ffffff",
      "--ts-var-calendar-cell-selected-background": "#ff385c",
      "--ts-var-button--secondary-hover-background": "#ececec",
      "--ts-var-button--secondary-active-background": "#e0e0e0",
      "--ts-var-button--secondary-hover-border-color": "#cacaca",
      "--ts-var-button--secondary-active-border-color": "#cacaca"
    }
  }
};
            export default appConfig;