const appConfig: any = {
  "liveboardId": "9ac8f2a5-1c28-4521-a4b0-27f6ecdbf119",
  "modelId": "4c235e98-46c4-49b2-b259-545e770e4a1c",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758024472,
  "app_config": {
    "menu_items": [
      "Dashboard",
      "Analytics",
      "Listings",
      "Reservations",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-root-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-viz-background": "#f7f7f7",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-root-hover-color": "#555555",
      "--ts-var-viz-border-color": "#dddddd",
      "--ts-var-viz-border-hover": "#cccccc",
      "--ts-var-viz-legend-color": "#333333",
      "--ts-var-root-active-color": "#222222",
      "--ts-var-viz-border-active": "#bbbbbb",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-viz-legend-border": "#dddddd",
      "--ts-var-menu-border-radius": "4px",
      "--ts-var-root-secondary-color": "#666666",
      "--ts-var-viz-background-hover": "#ffffff",
      "--ts-var-viz-box-shadow-hover": "0 4px 8px rgba(0, 0, 0, 0.2)",
      "--ts-var-menu-background-hover": "#f0f0f0",
      "--ts-var-menu-item-hover-color": "#333333",
      "--ts-var-viz-background-active": "#f0f0f0",
      "--ts-var-viz-box-shadow-active": "0 6px 12px rgba(0, 0, 0, 0.3)",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-legend-background": "#ffffff",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-viz-title-hover-color": "#ff5a5f",
      "--ts-var-menu-background-active": "#ffffff",
      "--ts-var-menu-item-active-color": "#ffffff",
      "--ts-var-menu-item-hover-border": "#ff5a5f",
      "--ts-var-viz-title-active-color": "#ff5a5f",
      "--ts-var-button--secondary-color": "#ffffff",
      "--ts-var-menu-item-active-border": "#ff5a5f",
      "--ts-var-menu-item-inactive-color": "#999999",
      "--ts-var-spotter-input-background": "#ffffff",
      "--ts-var-viz-title-inactive-color": "#999999",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-menu-item-inactive-border": "#dddddd",
      "--ts-var-spotter-prompt-background": "#f0f0f0",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#ff5a5f",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-description-hover-color": "#777777",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#ff5a5f",
      "--ts-var-spotter-input-disabled-color": "#aaaaaa",
      "--ts-var-viz-description-active-color": "#888888",
      "--ts-var-menu-item-hover-border-radius": "4px",
      "--ts-var-menu-item-inactive-background": "#ffffff",
      "--ts-var-spotter-prompt-disabled-color": "#aaaaaa",
      "--ts-var-menu-item-active-border-radius": "4px",
      "--ts-var-spotter-input-hover-background": "#f0f0f0",
      "--ts-var-viz-description-inactive-color": "#aaaaaa",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-spotter-prompt-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-disabled-color": "#666666",
      "--ts-var-viz-legend-item-hover-background": "#f0f0f0",
      "--ts-var-spotter-input-disabled-background": "#f0f0f0",
      "--ts-var-viz-legend-item-active-background": "#ff5a5f",
      "--ts-var-button--secondary-hover-background": "#ff4a4f",
      "--ts-var-spotter-prompt-disabled-background": "#e0e0e0",
      "--ts-var-button--secondary-active-background": "#ff3a3f",
      "--ts-var-button--secondary-disabled-background": "#cccccc"
    }
  }
};
            export default appConfig;