const appConfig: any = {
  "liveboardId": "6d210880-edaa-436e-87c0-835c24a4ed41",
  "modelId": "0e53c3f2-633c-43d4-8540-53bdebbe3045",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757411544,
  "color_schema": {
    "--ts-var-link-color": "#007a99",
    "--ts-var-root-color": "#333333",
    "--ts-var-card-border": "#dddddd",
    "--ts-var-card-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-menu-border": "#dddddd",
    "--ts-var-input-border": "#cccccc",
    "--ts-var-table-border": "#dddddd",
    "--ts-var-spinner-color": "#ffffff",
    "--ts-var-viz-background": "#ffffff",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-card-background": "#ffffff",
    "--ts-var-menu-background": "#ffffff",
    "--ts-var-menu-item-color": "#333333",
    "--ts-var-root-background": "#ffffff",
    "--ts-var-viz-title-color": "#333333",
    "--ts-var-badge-background": "#007a99",
    "--ts-var-badge-text-color": "#ffffff",
    "--ts-var-input-background": "#f9f9f9",
    "--ts-var-link-hover-color": "#005f7f",
    "--ts-var-modal-background": "#ffffff",
    "--ts-var-toast-background": "#333333",
    "--ts-var-toast-text-color": "#ffffff",
    "--ts-var-footer-background": "#f7f7f7",
    "--ts-var-footer-text-color": "#666666",
    "--ts-var-header-background": "#ffffff",
    "--ts-var-header-text-color": "#333333",
    "--ts-var-link-active-color": "#004d66",
    "--ts-var-pagination-border": "#dddddd",
    "--ts-var-table-cell-border": "#dddddd",
    "--ts-var-viz-border-radius": "8px",
    "--ts-var-input-focus-border": "#007a99",
    "--ts-var-spinner-background": "#007a99",
    "--ts-var-table-cell-padding": "12px",
    "--ts-var-tooltip-background": "#333333",
    "--ts-var-tooltip-text-color": "#ffffff",
    "--ts-var-table-row-background": "#ffffff",
    "--ts-var-table-row-text-color": "#333333",
    "--ts-var-card-hover-background": "#f7f7f7",
    "--ts-var-pagination-background": "#ffffff",
    "--ts-var-pagination-text-color": "#333333",
    "--ts-var-toast-info-background": "#17a2b8",
    "--ts-var-toast-info-text-color": "#ffffff",
    "--ts-var-viz-description-color": "#666666",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-badge-hover-background": "#005f7f",
    "--ts-var-card-active-background": "#e0e0e0",
    "--ts-var-toast-error-background": "#dc3545",
    "--ts-var-toast-error-text-color": "#ffffff",
    "--ts-var-badge-active-background": "#004d66",
    "--ts-var-button--secondary-color": "#333333",
    "--ts-var-input-placeholder-color": "#aaaaaa",
    "--ts-var-modal-footer-background": "#f7f7f7",
    "--ts-var-modal-footer-text-color": "#666666",
    "--ts-var-modal-header-background": "#f7f7f7",
    "--ts-var-modal-header-text-color": "#333333",
    "--ts-var-progress-bar-background": "#007a99",
    "--ts-var-table-header-background": "#f7f7f7",
    "--ts-var-table-header-text-color": "#333333",
    "--ts-var-modal-overlay-background": "rgba(0, 0, 0, 0.5)",
    "--ts-var-spotter-input-background": "#f2f2f2",
    "--ts-var-toast-success-background": "#28a745",
    "--ts-var-toast-success-text-color": "#ffffff",
    "--ts-var-toast-warning-background": "#ffc107",
    "--ts-var-toast-warning-text-color": "#333333",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#ffffff",
    "--ts-var-menu-item-hover-background": "#f7f7f7",
    "--ts-var-table-row-hover-background": "#f2f2f2",
    "--ts-var-menu-item-active-background": "#e0e0e0",
    "--ts-var-table-cell-hover-background": "#f2f2f2",
    "--ts-var-table-row-active-background": "#e0e0e0",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#e0e0e0",
    "--ts-var-button--secondary-background": "#f7f7f7",
    "--ts-var-button--secondary-text-color": "#333333",
    "--ts-var-pagination-active-background": "#007a99",
    "--ts-var-pagination-active-text-color": "#ffffff",
    "--ts-var-progress-bar-fill-background": "#005f7f",
    "--ts-var-table-cell-active-background": "#e0e0e0",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-hover-background": "#e0e0e0",
    "--ts-var-button--secondary-active-background": "#d5d5d5"
  }
};
            export default appConfig;