const appConfig: any = {
  "liveboardId": "2180098d-8dcb-48e5-8097-d2ab2c0aa83f",
  "modelId": "64a930d6-fbc8-4d62-af9c-88ba141b8e82",
  "host": "https://nebula-growth-spot-build.thoughtspotdev.cloud",
  "expires_at": 1758184698,
  "app_config": {
    "menu_items": [
      "Listings",
      "Analytics",
      "Reservations",
      "Messages",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-link-color": "#ff5a5f",
      "--ts-var-root-color": "#333333",
      "--ts-var-card-border": "#dddddd",
      "--ts-var-input-color": "#333333",
      "--ts-var-menu-border": "#dddddd",
      "--ts-var-input-border": "#dddddd",
      "--ts-var-tooltip-color": "#ffffff",
      "--ts-var-tooltip-border": "#dddddd",
      "--ts-var-viz-background": "#f7f7f7",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#ffffff",
      "--ts-var-card-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#ffffff",
      "--ts-var-menu-item-color": "#333333",
      "--ts-var-root-background": "#ffffff",
      "--ts-var-viz-title-color": "#333333",
      "--ts-var-input-background": "#ffffff",
      "--ts-var-link-focus-color": "#ff5a5f",
      "--ts-var-link-hover-color": "#ff4c4f",
      "--ts-var-card-focus-border": "#ff5a5f",
      "--ts-var-input-error-color": "#ff4c4f",
      "--ts-var-link-active-color": "#ff3f40",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-card-border-radius": "8px",
      "--ts-var-input-error-border": "#ff4c4f",
      "--ts-var-input-focus-border": "#ff5a5f",
      "--ts-var-tooltip-background": "#333333",
      "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-disabled-color": "#666666",
      "--ts-var-link-disabled-color": "#aaaaaa",
      "--ts-var-card-disabled-border": "#cccccc",
      "--ts-var-input-disabled-color": "#666666",
      "--ts-var-card-focus-box-shadow": "0 0 0 3px rgba(255, 90, 95, 0.5)",
      "--ts-var-card-hover-background": "#f7f7f7",
      "--ts-var-input-disabled-border": "#cccccc",
      "--ts-var-link-focus-box-shadow": "0 0 0 3px rgba(255, 90, 95, 0.5)",
      "--ts-var-viz-description-color": "#666666",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-card-active-background": "#f0f0f0",
      "--ts-var-input-error-background": "#fff4f4",
      "--ts-var-input-focus-box-shadow": "0 0 0 3px rgba(255, 90, 95, 0.5)",
      "--ts-var-button--secondary-color": "#ffffff",
      "--ts-var-input-placeholder-color": "#aaaaaa",
      "--ts-var-button--secondary-border": "#ff5a5f",
      "--ts-var-card-disabled-background": "#f0f0f0",
      "--ts-var-spotter-input-background": "#f0f0f0",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-input-disabled-background": "#f0f0f0",
      "--ts-var-spotter-prompt-background": "#ffffff",
      "--ts-var-menu-item-hover-background": "#f0f0f0",
      "--ts-var-menu-item-active-background": "#ff5a5f",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#e0e0e0",
      "--ts-var-button--secondary-background": "#ff5a5f",
      "--ts-var-button--secondary-focus-color": "#ffffff",
      "--ts-var-button--secondary-hover-color": "#ffffff",
      "--ts-var-input-error-placeholder-color": "#ff4c4f",
      "--ts-var-button--secondary-active-color": "#ffffff",
      "--ts-var-button--secondary-focus-border": "#ff5a5f",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-disabled-color": "#666666",
      "--ts-var-button--secondary-disabled-border": "#cccccc",
      "--ts-var-button--secondary-focus-background": "#ff4c4f",
      "--ts-var-button--secondary-focus-box-shadow": "0 0 0 3px rgba(255, 90, 95, 0.5)",
      "--ts-var-button--secondary-hover-background": "#ff4c4f",
      "--ts-var-button--secondary-active-background": "#ff3f40",
      "--ts-var-button--secondary-disabled-background": "#cccccc"
    }
  }
};
            export default appConfig;