const appConfig: any = {
  "liveboardId": "81c6cc27-1f06-4ac8-88bd-0090d8a16f0f",
  "modelId": "7df66826-554f-4cc1-a589-b62958b8dfca",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757409256,
  "color_schema": {
    "--ts-var-link-color": "#FF6F91",
    "--ts-var-root-color": "#3D3D3D",
    "--ts-var-badge-color": "#FFFFFF",
    "--ts-var-card-border": "#FFB3C1",
    "--ts-var-card-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-input-color": "#3D3D3D",
    "--ts-var-menu-border": "#FFB3C1",
    "--ts-var-input-border": "#FFB3C1",
    "--ts-var-modal-shadow": "0 4px 8px rgba(0, 0, 0, 0.2)",
    "--ts-var-badge-padding": "4px 8px",
    "--ts-var-divider-color": "#FFB3C1",
    "--ts-var-spinner-color": "#FF6F91",
    "--ts-var-tooltip-color": "#3D3D3D",
    "--ts-var-viz-background": "#FFFFFF",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-badge-font-size": "12px",
    "--ts-var-card-background": "#FFFFFF",
    "--ts-var-menu-background": "#FDE0E8",
    "--ts-var-menu-item-color": "#3D3D3D",
    "--ts-var-root-background": "#FDE0E8",
    "--ts-var-viz-title-color": "#FF6F91",
    "--ts-var-badge-background": "#FF6F91",
    "--ts-var-input-background": "#FFFFFF",
    "--ts-var-link-hover-color": "#FF4C7A",
    "--ts-var-modal-background": "#FFFFFF",
    "--ts-var-link-active-color": "#FF4C7A",
    "--ts-var-viz-border-radius": "8px",
    "--ts-var-card-border-radius": "8px",
    "--ts-var-modal-header-color": "#3D3D3D",
    "--ts-var-spinner-background": "#FFFFFF",
    "--ts-var-tooltip-background": "#FFB3C1",
    "--ts-var-badge-border-radius": "12px",
    "--ts-var-input-border-radius": "4px",
    "--ts-var-modal-border-radius": "8px",
    "--ts-var-button--primary-color": "#FFFFFF",
    "--ts-var-tooltip-border-radius": "4px",
    "--ts-var-viz-description-color": "#3D3D3D",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-button--secondary-color": "#FFFFFF",
    "--ts-var-input-placeholder-color": "#B0B0B0",
    "--ts-var-modal-footer-background": "#FFB3C1",
    "--ts-var-modal-header-background": "#FFB3C1",
    "--ts-var-spotter-input-background": "#FFFFFF",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#FDE0E8",
    "--ts-var-button--primary-background": "#FF6F91",
    "--ts-var-menu-item-hover-background": "#FFB3C1",
    "--ts-var-modal-header-border-bottom": "#FFB3C1",
    "--ts-var-menu-item-active-background": "#FF6F91",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-legend-hover-background": "#FFB3C1",
    "--ts-var-button--secondary-background": "#FF6F91",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--primary-hover-background": "#FF4C7A",
    "--ts-var-button--primary-active-background": "#FF4C7A",
    "--ts-var-button--secondary-hover-background": "#FFB3C1",
    "--ts-var-button--secondary-active-background": "#FFB3C1"
  }
};
            export default appConfig;