const appConfig: any = {
  "liveboardId": "2f19650f-9e9c-415d-8e54-ae50a356d4ed",
  "modelId": "bac2fccd-8776-4eab-97b3-af0208b53705",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757662010,
  "app_config": {
    "menu_items": [
      "Dashboard",
      "Analytics",
      "Products",
      "Orders",
      "Account Settings"
    ],
    "color_schema": {
      "--ts-var-link-color": "#FF3D5B",
      "--ts-var-root-color": "#4A4A4A",
      "--ts-var-card-border": "#FF6F91",
      "--ts-var-menu-border": "#FF6F91",
      "--ts-var-input-border": "#FF6F91",
      "--ts-var-modal-border": "#FF6F91",
      "--ts-var-divider-color": "#FFB3C1",
      "--ts-var-divider-style": "solid",
      "--ts-var-heading-color": "#4A4A4A",
      "--ts-var-spinner-color": "#FF6F91",
      "--ts-var-link-font-size": "16px",
      "--ts-var-viz-background": "#FFFFFF",
      "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-card-background": "#FFFFFF",
      "--ts-var-card-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-menu-background": "#FFFFFF",
      "--ts-var-menu-item-color": "#4A4A4A",
      "--ts-var-paragraph-color": "#4A4A4A",
      "--ts-var-root-background": "#FDE0E6",
      "--ts-var-viz-title-color": "#FF3D5B",
      "--ts-var-badge-background": "#FF6F91",
      "--ts-var-badge-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-badge-text-color": "#FFFFFF",
      "--ts-var-input-background": "#FFFFFF",
      "--ts-var-input-text-color": "#4A4A4A",
      "--ts-var-link-font-family": "Arial, sans-serif",
      "--ts-var-link-font-weight": "bold",
      "--ts-var-link-hover-color": "#FF2A4D",
      "--ts-var-modal-background": "#FFFFFF",
      "--ts-var-modal-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-divider-thickness": "1px",
      "--ts-var-heading-font-size": "24px",
      "--ts-var-link-active-color": "#FF6F91",
      "--ts-var-viz-border-radius": "8px",
      "--ts-var-card-border-radius": "8px",
      "--ts-var-spinner-background": "#FFFFFF",
      "--ts-var-spinner-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-tooltip-background": "#FFB3C1",
      "--ts-var-tooltip-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-tooltip-text-color": "#4A4A4A",
      "--ts-var-badge-border-radius": "12px",
      "--ts-var-heading-font-family": "Arial, sans-serif",
      "--ts-var-heading-font-weight": "bold",
      "--ts-var-input-border-radius": "4px",
      "--ts-var-modal-border-radius": "8px",
      "--ts-var-paragraph-font-size": "16px",
      "--ts-var-paragraph-font-family": "Arial, sans-serif",
      "--ts-var-paragraph-font-weight": "normal",
      "--ts-var-spinner-border-radius": "50%",
      "--ts-var-tooltip-border-radius": "4px",
      "--ts-var-viz-description-color": "#FF6F91",
      "--ts-var-viz-title-font-family": "Arial, sans-serif",
      "--ts-var-button--secondary-color": "#FFFFFF",
      "--ts-var-input-placeholder-color": "#B0B0B0",
      "--ts-var-button--secondary-border": "none",
      "--ts-var-spotter-input-background": "#FFFFFF",
      "--ts-var-viz-title-text-transform": "uppercase",
      "--ts-var-button--secondary-padding": "10px 20px",
      "--ts-var-spotter-prompt-background": "#FF6F91",
      "--ts-var-menu-item-hover-background": "#FFB3C1",
      "--ts-var-button--secondary-font-size": "16px",
      "--ts-var-menu-item-active-background": "#FF6F91",
      "--ts-var-viz-description-font-family": "Arial, sans-serif",
      "--ts-var-viz-legend-hover-background": "#FFB3C1",
      "--ts-var-button--secondary-background": "#FF6F91",
      "--ts-var-button--secondary-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
      "--ts-var-button--secondary-text-color": "#FFFFFF",
      "--ts-var-button--secondary-font-family": "Arial, sans-serif",
      "--ts-var-button--secondary-font-weight": "bold",
      "--ts-var-viz-description-text-transform": "none",
      "--ts-var-button--secondary-border-radius": "8px",
      "--ts-var-button--secondary-text-transform": "uppercase",
      "--ts-var-button--secondary-hover-background": "#FF3D5B",
      "--ts-var-button--secondary-active-background": "#FF2A4D"
    }
  }
};
            export default appConfig;