const appConfig: any = {
  "liveboardId": "197ea7e7-c126-4b1d-a0fe-c59c39754f89",
  "modelId": "61de0f0e-1871-4be3-8180-03c8ebdc8f77",
  "host": "https://nebula-spot-build-test.thoughtspotdev.cloud",
  "expires_at": 1757570602,
  "color_schema": {
    "--ts-var-root-color": "#000000",
    "--ts-var-menu-border": "#CCCCCC",
    "--ts-var-viz-background": "#FFFFFF",
    "--ts-var-viz-box-shadow": "0 2px 4px rgba(0, 0, 0, 0.1)",
    "--ts-var-menu-background": "#FFFFFF",
    "--ts-var-menu-item-color": "#007BFF",
    "--ts-var-root-background": "#F6EB61",
    "--ts-var-root-link-color": "#007BFF",
    "--ts-var-viz-title-color": "#000000",
    "--ts-var-viz-border-color": "#CCCCCC",
    "--ts-var-viz-border-hover": "#007BFF",
    "--ts-var-viz-border-active": "#0056b3",
    "--ts-var-viz-border-radius": "4px",
    "--ts-var-menu-border-radius": "4px",
    "--ts-var-viz-title-font-size": "24px",
    "--ts-var-root-secondary-color": "#333333",
    "--ts-var-spotter-input-border": "#CCCCCC",
    "--ts-var-viz-background-hover": "#F9F9F9",
    "--ts-var-button--primary-color": "#FFFFFF",
    "--ts-var-menu-item-hover-color": "#007BFF",
    "--ts-var-root-link-hover-color": "#0056b3",
    "--ts-var-viz-background-active": "#F0F0F0",
    "--ts-var-viz-description-color": "#333333",
    "--ts-var-viz-title-font-family": "Arial, sans-serif",
    "--ts-var-viz-title-font-weight": "bold",
    "--ts-var-viz-title-hover-color": "#007BFF",
    "--ts-var-viz-title-line-height": "1.5",
    "--ts-var-button--primary-border": "none",
    "--ts-var-menu-item-active-color": "#FFFFFF",
    "--ts-var-root-link-active-color": "#004494",
    "--ts-var-viz-title-active-color": "#007BFF",
    "--ts-var-button--secondary-color": "#FFFFFF",
    "--ts-var-menu-item-active-border": "#007BFF",
    "--ts-var-menu-item-border-radius": "4px",
    "--ts-var-button--secondary-border": "none",
    "--ts-var-spotter-input-background": "#FFFFFF",
    "--ts-var-viz-title-letter-spacing": "0.5px",
    "--ts-var-viz-title-text-transform": "uppercase",
    "--ts-var-spotter-prompt-background": "#F0F0F0",
    "--ts-var-viz-description-font-size": "16px",
    "--ts-var-button--primary-background": "#007BFF",
    "--ts-var-menu-item-hover-background": "#E0E0E0",
    "--ts-var-spotter-input-hover-border": "#007BFF",
    "--ts-var-viz-title-hover-background": "#F0F0F0",
    "--ts-var-menu-item-active-background": "#D0D0D0",
    "--ts-var-spotter-input-active-border": "#007BFF",
    "--ts-var-viz-description-font-family": "Arial, sans-serif",
    "--ts-var-viz-description-font-weight": "normal",
    "--ts-var-viz-description-hover-color": "#007BFF",
    "--ts-var-viz-description-line-height": "1.5",
    "--ts-var-viz-legend-hover-background": "#E0E0E0",
    "--ts-var-button--secondary-background": "#007BFF",
    "--ts-var-menu-item-active-color-hover": "#FFFFFF",
    "--ts-var-viz-description-active-color": "#007BFF",
    "--ts-var-button--primary-border-radius": "4px",
    "--ts-var-menu-item-hover-border-radius": "4px",
    "--ts-var-menu-item-active-border-radius": "4px",
    "--ts-var-viz-description-letter-spacing": "0.5px",
    "--ts-var-viz-description-text-transform": "none",
    "--ts-var-button--secondary-border-radius": "4px",
    "--ts-var-spotter-input-active-background": "#E0E0E0",
    "--ts-var-button--primary-hover-background": "#0056b3",
    "--ts-var-viz-description-hover-background": "#F0F0F0",
    "--ts-var-button--primary-active-background": "#004494",
    "--ts-var-menu-item-active-background-hover": "#0056b3",
    "--ts-var-menu-item-hover-background-active": "#007BFF",
    "--ts-var-button--secondary-hover-background": "#0056b3",
    "--ts-var-button--secondary-active-background": "#004494"
  }
};
            export default appConfig;